#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(60, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("ai_dialogue_globals", "adlg", "����", typeof(AiDialogueGlobalsBlock))]
    public class AiDialogueGlobalsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("vocalizations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Vocalization Definitions Block 0", 500, typeof(VocalizationDefinitionsBlock0))]
        public TagBlock Vocalizations;
        [Abide.Guerilla.Tags.FieldAttribute("patterns", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Vocalization Patterns Block", 1000, typeof(VocalizationPatternsBlock))]
        public TagBlock Patterns;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("dialogue data", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Dialogue Data Block", 200, typeof(DialogueDataBlock))]
        public TagBlock DialogueData;
        [Abide.Guerilla.Tags.FieldAttribute("involuntary data", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Involuntary Data Block", 100, typeof(InvoluntaryDataBlock))]
        public TagBlock InvoluntaryData;
    }
}
#pragma warning restore CS1591
