#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(12, 4)]
    public class AiGlobalsGravemindBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("min retreat time:secs", typeof(Single))]
        public Single MinRetreatTime;
        [Abide.Guerilla.Tags.FieldAttribute("ideal retreat time:secs", typeof(Single))]
        public Single IdealRetreatTime;
        [Abide.Guerilla.Tags.FieldAttribute("max retreat time:secs", typeof(Single))]
        public Single MaxRetreatTime;
    }
}
#pragma warning restore CS1591
