#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class AiSceneBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name^", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("trigger conditions", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Scene Trigger Block", 1, typeof(AiSceneTriggerBlock))]
        public TagBlock TriggerConditions;
        [Abide.Guerilla.Tags.FieldAttribute("roles", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Scene Role Block", 10, typeof(AiSceneRoleBlock))]
        public TagBlock Roles;
        public enum FlagsOptions
        {
            SceneCanPlayMultipleTimes = 1,
            EnableCombatDialogue = 2,
        }
    }
}
#pragma warning restore CS1591
