#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(128, 4)]
    public class AntennaVertexBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("spring strength coefficient#strength of the spring (larger values make the spring" +
            " stronger)", typeof(Single))]
        public Single SpringStrengthCoefficient;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(24)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("angles#direction toward next vertex", typeof(Vector2))]
        public Vector2 Angles;
        [Abide.Guerilla.Tags.FieldAttribute("length:world units#distance between this vertex and the next", typeof(Single))]
        public Single Length;
        [Abide.Guerilla.Tags.FieldAttribute("sequence index#bitmap group sequence index for this vertex\'s texture", typeof(Int16))]
        public Int16 SequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("color#color at this vertex", typeof(ColorArgbF))]
        public ColorArgbF Color;
        [Abide.Guerilla.Tags.FieldAttribute("LOD color#color at this vertex for the low-LOD line primitives", typeof(ColorArgbF))]
        public ColorArgbF LodColor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(40)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString3;
    }
}
#pragma warning restore CS1591
