#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(76, 4)]
    public class AntiGravityPointDefinitionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("marker name^", typeof(StringId))]
        public StringId MarkerName;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav strength", typeof(Single))]
        public Single AntigravStrength;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav offset", typeof(Single))]
        public Single AntigravOffset;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav height", typeof(Single))]
        public Single AntigravHeight;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav damp factor", typeof(Single))]
        public Single AntigravDampFactor;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav normal k1", typeof(Single))]
        public Single AntigravNormalK1;
        [Abide.Guerilla.Tags.FieldAttribute("antigrav normal k0", typeof(Single))]
        public Single AntigravNormalK0;
        [Abide.Guerilla.Tags.FieldAttribute("radius", typeof(Single))]
        public Single Radius;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("damage source region name", typeof(StringId))]
        public StringId DamageSourceRegionName;
        [Abide.Guerilla.Tags.FieldAttribute("default state error", typeof(Single))]
        public Single DefaultStateError;
        [Abide.Guerilla.Tags.FieldAttribute("minor damage error", typeof(Single))]
        public Single MinorDamageError;
        [Abide.Guerilla.Tags.FieldAttribute("medium damage error", typeof(Single))]
        public Single MediumDamageError;
        [Abide.Guerilla.Tags.FieldAttribute("major damage error", typeof(Single))]
        public Single MajorDamageError;
        [Abide.Guerilla.Tags.FieldAttribute("destroyed state error", typeof(Single))]
        public Single DestroyedStateError;
        public enum FlagsOptions
        {
            GetsDamageFromRegion = 1,
        }
    }
}
#pragma warning restore CS1591
