#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(64, 4)]
    public class BitmapGroupSequenceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name^", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("First Bitmap Index*", typeof(Int16))]
        public Int16 FirstBitmapIndex;
        [Abide.Guerilla.Tags.FieldAttribute("Bitmap Count*", typeof(Int16))]
        public Int16 BitmapCount;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Sprites*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Bitmap Group Sprite Block", 64, typeof(BitmapGroupSpriteBlock))]
        public TagBlock Sprites;
    }
}
#pragma warning restore CS1591
