#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class BitmapGroupSpriteBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Bitmap Index*", typeof(Int16))]
        public Int16 BitmapIndex;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Left*", typeof(Single))]
        public Single Left;
        [Abide.Guerilla.Tags.FieldAttribute("Right*", typeof(Single))]
        public Single Right;
        [Abide.Guerilla.Tags.FieldAttribute("Top*", typeof(Single))]
        public Single Top;
        [Abide.Guerilla.Tags.FieldAttribute("Bottom*", typeof(Single))]
        public Single Bottom;
        [Abide.Guerilla.Tags.FieldAttribute("Registration Point*", typeof(Vector2))]
        public Vector2 RegistrationPoint;
    }
}
#pragma warning restore CS1591
