#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class BreakableSurfaceKeyTableBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("*Instanced Geometry Index", typeof(Int16))]
        public Int16 EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("*Breakable Surface Index", typeof(Int16))]
        public Int16 EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("*Seed Surface Index", typeof(Int32))]
        public Int32 EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("*x0", typeof(Single))]
        public Single EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("*x1", typeof(Single))]
        public Single EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("*y0", typeof(Single))]
        public Single EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("*y1", typeof(Single))]
        public Single EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("*z0", typeof(Single))]
        public Single EmptyString7;
        [Abide.Guerilla.Tags.FieldAttribute("*z1", typeof(Single))]
        public Single EmptyString8;
    }
}
#pragma warning restore CS1591
