#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("cache_file_sound", "$#!+", "����", typeof(CacheFileSoundBlock))]
    public class CacheFileSoundBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("sound class*", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(SoundClass), false)]
        public Byte SoundClass1;
        [Abide.Guerilla.Tags.FieldAttribute("sample rate*", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(SampleRate), false)]
        public Byte SampleRate1;
        [Abide.Guerilla.Tags.FieldAttribute("encoding*", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(Encoding), false)]
        public Byte Encoding1;
        [Abide.Guerilla.Tags.FieldAttribute("compression*", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(Compression), false)]
        public Byte Compression1;
        [Abide.Guerilla.Tags.FieldAttribute("playback index", typeof(Int16))]
        public Int16 PlaybackIndex;
        [Abide.Guerilla.Tags.FieldAttribute("first pitch range index", typeof(Int16))]
        public Int16 FirstPitchRangeIndex;
        [Abide.Guerilla.Tags.FieldAttribute("pitch range count", typeof(Byte))]
        public Byte PitchRangeCount;
        [Abide.Guerilla.Tags.FieldAttribute("scale index", typeof(Byte))]
        public Byte ScaleIndex;
        [Abide.Guerilla.Tags.FieldAttribute("promotion index", typeof(Byte))]
        public Byte PromotionIndex;
        [Abide.Guerilla.Tags.FieldAttribute("custom playback index", typeof(Byte))]
        public Byte CustomPlaybackIndex;
        [Abide.Guerilla.Tags.FieldAttribute("extra info index", typeof(Int16))]
        public Int16 ExtraInfoIndex;
        [Abide.Guerilla.Tags.FieldAttribute("maximum play time:ms", typeof(Int32))]
        public Int32 MaximumPlayTime;
        public enum FlagsOptions
        {
            FitToAdpcmBlocksize = 1,
            SplitLongSoundIntoPermutations = 2,
            AlwaysSpatialize = 4,
            NeverObstruct = 8,
            InternalDontTouch = 16,
            UseHugeSoundTransmission = 32,
            LinkCountToOwnerUnit = 64,
            PitchRangeIsLanguage = 128,
            DontUseSoundClassSpeakerFlag = 256,
            DontUseLipsyncData = 512,
        }
        public enum SoundClass
        {
            ProjectileImpact = 0,
            ProjectileDetonation = 1,
            ProjectileFlyby = 2,
            EmptyString = 3,
            WeaponFire = 4,
            WeaponReady = 5,
            WeaponReload = 6,
            WeaponEmpty = 7,
            WeaponCharge = 8,
            WeaponOverheat = 9,
            WeaponIdle = 10,
            WeaponMelee = 11,
            WeaponAnimation = 12,
            ObjectImpacts = 13,
            ParticleImpacts = 14,
            EmptyString1 = 15,
            EmptyString2 = 16,
            EmptyString3 = 17,
            UnitFootsteps = 18,
            UnitDialog = 19,
            UnitAnimation = 20,
            EmptyString4 = 21,
            VehicleCollision = 22,
            VehicleEngine = 23,
            VehicleAnimation = 24,
            EmptyString5 = 25,
            DeviceDoor = 26,
            EmptyString6 = 27,
            DeviceMachinery = 28,
            DeviceStationary = 29,
            EmptyString7 = 30,
            EmptyString8 = 31,
            Music = 32,
            AmbientNature = 33,
            AmbientMachinery = 34,
            EmptyString9 = 35,
            HugeAss = 36,
            ObjectLooping = 37,
            CinematicMusic = 38,
            EmptyString10 = 39,
            EmptyString11 = 40,
            EmptyString12 = 41,
            EmptyString13 = 42,
            EmptyString14 = 43,
            EmptyString15 = 44,
            CortanaMission = 45,
            CortanaCinematic = 46,
            MissionDialog = 47,
            CinematicDialog = 48,
            ScriptedCinematicFoley = 49,
            GameEvent = 50,
            Ui = 51,
            Test = 52,
            MultilingualTest = 53,
        }
        public enum SampleRate
        {
            _22khz = 0,
            _44khz = 1,
            _32khz = 2,
        }
        public enum Encoding
        {
            Mono = 0,
            Stereo = 1,
            Codec = 2,
        }
        public enum Compression
        {
            NoneBigEndian = 0,
            XboxAdpcm = 1,
            ImaAdpcm = 2,
            NoneLittleEndian = 3,
            Wma = 4,
        }
    }
}
#pragma warning restore CS1591
