#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(52, 4)]
    public class CharacterPerceptionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("perception flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(PerceptionFlagsOptions), true)]
        public Int32 PerceptionFlags;
        [Abide.Guerilla.Tags.FieldAttribute("max vision distance:world units#maximum range of sight", typeof(Single))]
        public Single MaxVisionDistance;
        [Abide.Guerilla.Tags.FieldAttribute("central vision angle:degrees#horizontal angle within which we see targets out to " +
            "our maximum range", typeof(Single))]
        public Single CentralVisionAngle;
        [Abide.Guerilla.Tags.FieldAttribute("max vision angle:degrees#maximum horizontal angle within which we see targets at " +
            "range", typeof(Single))]
        public Single MaxVisionAngle;
        [Abide.Guerilla.Tags.FieldAttribute("peripheral vision angle:degrees#maximum horizontal angle within which we can see " +
            "targets out of the corner of our eye", typeof(Single))]
        public Single PeripheralVisionAngle;
        [Abide.Guerilla.Tags.FieldAttribute("peripheral distance:world units#maximum range at which we can see targets our of " +
            "the corner of our eye", typeof(Single))]
        public Single PeripheralDistance;
        [Abide.Guerilla.Tags.FieldAttribute("hearing distance:world units#maximum range at which sounds can be heard", typeof(Single))]
        public Single HearingDistance;
        [Abide.Guerilla.Tags.FieldAttribute("notice projectile chance:[0,1]#random chance of noticing a dangerous enemy projec" +
            "tile (e.g. grenade)", typeof(Single))]
        public Single NoticeProjectileChance;
        [Abide.Guerilla.Tags.FieldAttribute("notice vehicle chance:[0,1]#random chance of noticing a dangerous vehicle", typeof(Single))]
        public Single NoticeVehicleChance;
        [Abide.Guerilla.Tags.FieldAttribute("combat perception time:seconds#time required to acknowledge a visible enemy when " +
            "we are already in combat or searching for them", typeof(Single))]
        public Single CombatPerceptionTime;
        [Abide.Guerilla.Tags.FieldAttribute("guard perception time:seconds#time required to acknowledge a visible enemy when w" +
            "e have been alerted", typeof(Single))]
        public Single GuardPerceptionTime;
        [Abide.Guerilla.Tags.FieldAttribute("non-combat perception time:seconds#time required to acknowledge a visible enemy w" +
            "hen we are not alerted", typeof(Single))]
        public Single NoncombatPerceptionTime;
        [Abide.Guerilla.Tags.FieldAttribute("first ack. surprise distance:world units#If a new prop is acknowledged within the" +
            " given distance, surprise is registerd", typeof(Single))]
        public Single FirstAckSurpriseDistance;
        public enum PerceptionFlagsOptions
        {
            Flag1 = 1,
        }
    }
}
#pragma warning restore CS1591
