#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(36, 4)]
    public class CharacterPresearchBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Pre-search flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(PresearchFlagsOptions), true)]
        public Int32 PresearchFlags;
        [Abide.Guerilla.Tags.FieldAttribute("Min certainty radius", typeof(Single))]
        public Single MinCertaintyRadius;
        [Abide.Guerilla.Tags.FieldAttribute("DEPRECATED", typeof(Single))]
        public Single Deprecated;
        public enum PresearchFlagsOptions
        {
            Flag1 = 1,
        }
    }
}
#pragma warning restore CS1591
