#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(132, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("cloth", "clwd", "����", typeof(ClothBlock))]
    public class ClothBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("marker attachment name", typeof(StringId))]
        public StringId MarkerAttachmentName;
        [Abide.Guerilla.Tags.FieldAttribute("Shader", typeof(TagReference))]
        public TagReference Shader;
        [Abide.Guerilla.Tags.FieldAttribute("grid x dimension", typeof(Int16))]
        public Int16 GridXDimension;
        [Abide.Guerilla.Tags.FieldAttribute("grid y dimension", typeof(Int16))]
        public Int16 GridYDimension;
        [Abide.Guerilla.Tags.FieldAttribute("grid spacing x", typeof(Single))]
        public Single GridSpacingX;
        [Abide.Guerilla.Tags.FieldAttribute("grid spacing y", typeof(Single))]
        public Single GridSpacingY;
        [Abide.Guerilla.Tags.FieldAttribute("properties", typeof(ClothPropertiesBlock))]
        public ClothPropertiesBlock Properties;
        [Abide.Guerilla.Tags.FieldAttribute("vertices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cloth Vertices Block", 128, typeof(ClothVerticesBlock))]
        public TagBlock Vertices;
        [Abide.Guerilla.Tags.FieldAttribute("indices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cloth Indices Block", 768, typeof(ClothIndicesBlock))]
        public TagBlock Indices;
        [Abide.Guerilla.Tags.FieldAttribute("strip indices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cloth Indices Block", 768, typeof(ClothIndicesBlock))]
        public TagBlock StripIndices;
        [Abide.Guerilla.Tags.FieldAttribute("links*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cloth Links Block", 640, typeof(ClothLinksBlock))]
        public TagBlock Links;
        public enum FlagsOptions
        {
            DoesntUseWind = 1,
            UsesGridAttachTop = 2,
        }
    }
}
#pragma warning restore CS1591
