#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(80, 4)]
    public class CollisionDamageBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("collision damage", typeof(TagReference))]
        public TagReference CollisionDamage;
        [Abide.Guerilla.Tags.FieldAttribute("min game acc (default)#0-oo", typeof(Single))]
        public Single MinGameAccDefault;
        [Abide.Guerilla.Tags.FieldAttribute("max game acc (default)#0-oo", typeof(Single))]
        public Single MaxGameAccDefault;
        [Abide.Guerilla.Tags.FieldAttribute("min game scale (default)#0-1", typeof(Single))]
        public Single MinGameScaleDefault;
        [Abide.Guerilla.Tags.FieldAttribute("max game scale (default)#0-1", typeof(Single))]
        public Single MaxGameScaleDefault;
        [Abide.Guerilla.Tags.FieldAttribute("min abs acc (default)#0-oo", typeof(Single))]
        public Single MinAbsAccDefault;
        [Abide.Guerilla.Tags.FieldAttribute("max abs acc (default)#0-oo", typeof(Single))]
        public Single MaxAbsAccDefault;
        [Abide.Guerilla.Tags.FieldAttribute("min abs scale (default)#0-1", typeof(Single))]
        public Single MinAbsScaleDefault;
        [Abide.Guerilla.Tags.FieldAttribute("max abs scale (default)#0-1", typeof(Single))]
        public Single MaxAbsScaleDefault;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString;
    }
}
#pragma warning restore CS1591
