#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(52, 4)]
    public class CsPointSetBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name^", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("points", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cs Point Block", 20, typeof(CsPointBlock))]
        public TagBlock Points;
        [Abide.Guerilla.Tags.FieldAttribute("bsp index", typeof(Int16))]
        public Int16 BspIndex;
        [Abide.Guerilla.Tags.FieldAttribute("manual reference frame", typeof(Int16))]
        public Int16 ManualReferenceFrame;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        public enum FlagsOptions
        {
            ManualReferenceFrame = 1,
            TurretDeployment = 2,
        }
    }
}
#pragma warning restore CS1591
