#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class DamageAnimationBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("label^", typeof(StringId))]
        public StringId Label;
        [Abide.Guerilla.Tags.FieldAttribute("directions*|AABBCC", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Damage Direction Block", 4, typeof(DamageDirectionBlock))]
        public TagBlock Directions;
    }
}
#pragma warning restore CS1591
