#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(64, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("decorators", "DECP", "����", typeof(DecoratorsBlock))]
    public class DecoratorsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Grid Origin", typeof(Vector3))]
        public Vector3 GridOrigin;
        [Abide.Guerilla.Tags.FieldAttribute("Cell Count per Dimension", typeof(Int32))]
        public Int32 CellCountPerDimension;
        [Abide.Guerilla.Tags.FieldAttribute("Cache Blocks", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Decorator Cache Block Block", 4096, typeof(DecoratorCacheBlockBlock))]
        public TagBlock CacheBlocks;
        [Abide.Guerilla.Tags.FieldAttribute("Groups", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Decorator Group Block", 131072, typeof(DecoratorGroupBlock))]
        public TagBlock Groups;
        [Abide.Guerilla.Tags.FieldAttribute("Cells", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Decorator Cell Collection Block", 65535, typeof(DecoratorCellCollectionBlock))]
        public TagBlock Cells;
        [Abide.Guerilla.Tags.FieldAttribute("Decals", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Decorator Projected Decal Block", 32768, typeof(DecoratorProjectedDecalBlock))]
        public TagBlock Decals;
    }
}
#pragma warning restore CS1591
