#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(24, 4)]
    public class DecoratorGroupBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Decorator Set*", typeof(Byte))]
        public Byte DecoratorSet;
        [Abide.Guerilla.Tags.FieldAttribute("Decorator Type", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(DecoratorTypeOptions), false)]
        public Byte DecoratorType;
        [Abide.Guerilla.Tags.FieldAttribute("Shader Index*", typeof(Byte))]
        public Byte ShaderIndex;
        [Abide.Guerilla.Tags.FieldAttribute("Compressed Radius*", typeof(Byte))]
        public Byte CompressedRadius;
        [Abide.Guerilla.Tags.FieldAttribute("Cluster*", typeof(Int16))]
        public Int16 Cluster;
        [Abide.Guerilla.Tags.FieldAttribute("Cache Block*", typeof(Int16))]
        public Int16 CacheBlock;
        [Abide.Guerilla.Tags.FieldAttribute("Decorator Start Index*", typeof(Int16))]
        public Int16 DecoratorStartIndex;
        [Abide.Guerilla.Tags.FieldAttribute("Decorator Count*", typeof(Int16))]
        public Int16 DecoratorCount;
        [Abide.Guerilla.Tags.FieldAttribute("Vertex Start Offset*", typeof(Int16))]
        public Int16 VertexStartOffset;
        [Abide.Guerilla.Tags.FieldAttribute("Vertex Count*", typeof(Int16))]
        public Int16 VertexCount;
        [Abide.Guerilla.Tags.FieldAttribute("Index Start Offset*", typeof(Int16))]
        public Int16 IndexStartOffset;
        [Abide.Guerilla.Tags.FieldAttribute("Index Count*", typeof(Int16))]
        public Int16 IndexCount;
        [Abide.Guerilla.Tags.FieldAttribute("Compressed Bounding Center*", typeof(Int32))]
        public Int32 CompressedBoundingCenter;
        public enum DecoratorTypeOptions
        {
            Model = 0,
            FloatingDecal = 1,
            ProjectedDecal = 2,
            ScreenFacingQuad = 3,
            AxisRotatingQuad = 4,
            CrossQuad = 5,
        }
    }
}
#pragma warning restore CS1591
