#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(128, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("detail_object_collection", "dobc", "����", typeof(DetailObjectCollectionBlock))]
    public class DetailObjectCollectionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Collection Type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(CollectionTypeOptions), false)]
        public Int16 CollectionType;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Global z Offset: Applied to all detail objects in this collection so they don\'t f" +
            "loat above the ground.", typeof(Single))]
        public Single GlobalZOffset;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(44)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Sprite Plate", typeof(TagReference))]
        public TagReference SpritePlate;
        [Abide.Guerilla.Tags.FieldAttribute("Types", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Detail Object Type Block", 16, typeof(DetailObjectTypeBlock))]
        public TagBlock Types;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(48)]
        public Byte[] EmptyString2;
        public enum CollectionTypeOptions
        {
            Screenfacing = 0,
            Viewerfacing = 1,
        }
    }
}
#pragma warning restore CS1591
