#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(96, 4)]
    public class DetailObjectTypeBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name^", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("Sequence Index:[0,15]", typeof(Byte))]
        public Byte SequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("type flags", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(TypeFlagsOptions), true)]
        public Byte TypeFlags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Color Override Factor#Fraction of detail object color to use instead of the base " +
            "map color in the environment:[0,1]", typeof(Single))]
        public Single ColorOverrideFactor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Near Fade Distance:world units", typeof(Single))]
        public Single NearFadeDistance;
        [Abide.Guerilla.Tags.FieldAttribute("Far Fade Distance:world units", typeof(Single))]
        public Single FarFadeDistance;
        [Abide.Guerilla.Tags.FieldAttribute("Size:world units per pixel", typeof(Single))]
        public Single Size;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("Minimum Color:[0,1]", typeof(ColorRgbF))]
        public ColorRgbF MinimumColor;
        [Abide.Guerilla.Tags.FieldAttribute("Maximum Color:[0,1]", typeof(ColorRgbF))]
        public ColorRgbF MaximumColor;
        [Abide.Guerilla.Tags.FieldAttribute("ambient color:[0,255]", typeof(ColorArgb))]
        public ColorArgb AmbientColor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString3;
        public enum TypeFlagsOptions
        {
            Unused = 1,
            Unused1 = 2,
            InterpolateColorInHsv = 4,
            MoreColors = 8,
        }
    }
}
#pragma warning restore CS1591
