#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(644, 4)]
    public class DifficultyBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("easy enemy damage#enemy damage multiplier on easy difficulty", typeof(Single))]
        public Single EasyEnemyDamage;
        [Abide.Guerilla.Tags.FieldAttribute("normal enemy damage#enemy damage multiplier on normal difficulty", typeof(Single))]
        public Single NormalEnemyDamage;
        [Abide.Guerilla.Tags.FieldAttribute("hard enemy damage#enemy damage multiplier on hard difficulty", typeof(Single))]
        public Single HardEnemyDamage;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. enemy damage#enemy damage multiplier on impossible difficulty", typeof(Single))]
        public Single ImpossEnemyDamage;
        [Abide.Guerilla.Tags.FieldAttribute("easy enemy vitality#enemy maximum body vitality scale on easy difficulty", typeof(Single))]
        public Single EasyEnemyVitality;
        [Abide.Guerilla.Tags.FieldAttribute("normal enemy vitality#enemy maximum body vitality scale on normal difficulty", typeof(Single))]
        public Single NormalEnemyVitality;
        [Abide.Guerilla.Tags.FieldAttribute("hard enemy vitality#enemy maximum body vitality scale on hard difficulty", typeof(Single))]
        public Single HardEnemyVitality;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. enemy vitality#enemy maximum body vitality scale on impossible difficulty" +
            "", typeof(Single))]
        public Single ImpossEnemyVitality;
        [Abide.Guerilla.Tags.FieldAttribute("easy enemy shield#enemy maximum shield vitality scale on easy difficulty", typeof(Single))]
        public Single EasyEnemyShield;
        [Abide.Guerilla.Tags.FieldAttribute("normal enemy shield#enemy maximum shield vitality scale on normal difficulty", typeof(Single))]
        public Single NormalEnemyShield;
        [Abide.Guerilla.Tags.FieldAttribute("hard enemy shield#enemy maximum shield vitality scale on hard difficulty", typeof(Single))]
        public Single HardEnemyShield;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. enemy shield#enemy maximum shield vitality scale on impossible difficulty" +
            "", typeof(Single))]
        public Single ImpossEnemyShield;
        [Abide.Guerilla.Tags.FieldAttribute("easy enemy recharge#enemy shield recharge scale on easy difficulty", typeof(Single))]
        public Single EasyEnemyRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("normal enemy recharge#enemy shield recharge scale on normal difficulty", typeof(Single))]
        public Single NormalEnemyRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("hard enemy recharge#enemy shield recharge scale on hard difficulty", typeof(Single))]
        public Single HardEnemyRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. enemy recharge#enemy shield recharge scale on impossible difficulty", typeof(Single))]
        public Single ImpossEnemyRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("easy friend damage#friend damage multiplier on easy difficulty", typeof(Single))]
        public Single EasyFriendDamage;
        [Abide.Guerilla.Tags.FieldAttribute("normal friend damage#friend damage multiplier on normal difficulty", typeof(Single))]
        public Single NormalFriendDamage;
        [Abide.Guerilla.Tags.FieldAttribute("hard friend damage#friend damage multiplier on hard difficulty", typeof(Single))]
        public Single HardFriendDamage;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. friend damage#friend damage multiplier on impossible difficulty", typeof(Single))]
        public Single ImpossFriendDamage;
        [Abide.Guerilla.Tags.FieldAttribute("easy friend vitality#friend maximum body vitality scale on easy difficulty", typeof(Single))]
        public Single EasyFriendVitality;
        [Abide.Guerilla.Tags.FieldAttribute("normal friend vitality#friend maximum body vitality scale on normal difficulty", typeof(Single))]
        public Single NormalFriendVitality;
        [Abide.Guerilla.Tags.FieldAttribute("hard friend vitality#friend maximum body vitality scale on hard difficulty", typeof(Single))]
        public Single HardFriendVitality;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. friend vitality#friend maximum body vitality scale on impossible difficul" +
            "ty", typeof(Single))]
        public Single ImpossFriendVitality;
        [Abide.Guerilla.Tags.FieldAttribute("easy friend shield#friend maximum shield vitality scale on easy difficulty", typeof(Single))]
        public Single EasyFriendShield;
        [Abide.Guerilla.Tags.FieldAttribute("normal friend shield#friend maximum shield vitality scale on normal difficulty", typeof(Single))]
        public Single NormalFriendShield;
        [Abide.Guerilla.Tags.FieldAttribute("hard friend shield#friend maximum shield vitality scale on hard difficulty", typeof(Single))]
        public Single HardFriendShield;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. friend shield#friend maximum shield vitality scale on impossible difficul" +
            "ty", typeof(Single))]
        public Single ImpossFriendShield;
        [Abide.Guerilla.Tags.FieldAttribute("easy friend recharge#friend shield recharge scale on easy difficulty", typeof(Single))]
        public Single EasyFriendRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("normal friend recharge#friend shield recharge scale on normal difficulty", typeof(Single))]
        public Single NormalFriendRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("hard friend recharge#friend shield recharge scale on hard difficulty", typeof(Single))]
        public Single HardFriendRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. friend recharge#friend shield recharge scale on impossible difficulty", typeof(Single))]
        public Single ImpossFriendRecharge;
        [Abide.Guerilla.Tags.FieldAttribute("easy infection forms#toughness of infection forms (may be negative) on easy diffi" +
            "culty", typeof(Single))]
        public Single EasyInfectionForms;
        [Abide.Guerilla.Tags.FieldAttribute("normal infection forms#toughness of infection forms (may be negative) on normal d" +
            "ifficulty", typeof(Single))]
        public Single NormalInfectionForms;
        [Abide.Guerilla.Tags.FieldAttribute("hard infection forms#toughness of infection forms (may be negative) on hard diffi" +
            "culty", typeof(Single))]
        public Single HardInfectionForms;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. infection forms#toughness of infection forms (may be negative) on impossi" +
            "ble difficulty", typeof(Single))]
        public Single ImpossInfectionForms;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("easy rate of fire#enemy rate of fire scale on easy difficulty", typeof(Single))]
        public Single EasyRateOfFire;
        [Abide.Guerilla.Tags.FieldAttribute("normal rate of fire#enemy rate of fire scale on normal difficulty", typeof(Single))]
        public Single NormalRateOfFire;
        [Abide.Guerilla.Tags.FieldAttribute("hard rate of fire#enemy rate of fire scale on hard difficulty", typeof(Single))]
        public Single HardRateOfFire;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. rate of fire#enemy rate of fire scale on impossible difficulty", typeof(Single))]
        public Single ImpossRateOfFire;
        [Abide.Guerilla.Tags.FieldAttribute("easy projectile error#enemy projectile error scale, as a fraction of their base f" +
            "iring error. on easy difficulty", typeof(Single))]
        public Single EasyProjectileError;
        [Abide.Guerilla.Tags.FieldAttribute("normal projectile error#enemy projectile error scale, as a fraction of their base" +
            " firing error. on normal difficulty", typeof(Single))]
        public Single NormalProjectileError;
        [Abide.Guerilla.Tags.FieldAttribute("hard projectile error#enemy projectile error scale, as a fraction of their base f" +
            "iring error. on hard difficulty", typeof(Single))]
        public Single HardProjectileError;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. projectile error#enemy projectile error scale, as a fraction of their bas" +
            "e firing error. on impossible difficulty", typeof(Single))]
        public Single ImpossProjectileError;
        [Abide.Guerilla.Tags.FieldAttribute("easy burst error#enemy burst error scale; reduces intra-burst shot distance. on e" +
            "asy difficulty", typeof(Single))]
        public Single EasyBurstError;
        [Abide.Guerilla.Tags.FieldAttribute("normal burst error#enemy burst error scale; reduces intra-burst shot distance. on" +
            " normal difficulty", typeof(Single))]
        public Single NormalBurstError;
        [Abide.Guerilla.Tags.FieldAttribute("hard burst error#enemy burst error scale; reduces intra-burst shot distance. on h" +
            "ard difficulty", typeof(Single))]
        public Single HardBurstError;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. burst error#enemy burst error scale; reduces intra-burst shot distance. o" +
            "n impossible difficulty", typeof(Single))]
        public Single ImpossBurstError;
        [Abide.Guerilla.Tags.FieldAttribute("easy new target delay#enemy new-target delay scale factor. on easy difficulty", typeof(Single))]
        public Single EasyNewTargetDelay;
        [Abide.Guerilla.Tags.FieldAttribute("normal new target delay#enemy new-target delay scale factor. on normal difficulty" +
            "", typeof(Single))]
        public Single NormalNewTargetDelay;
        [Abide.Guerilla.Tags.FieldAttribute("hard new target delay#enemy new-target delay scale factor. on hard difficulty", typeof(Single))]
        public Single HardNewTargetDelay;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. new target delay#enemy new-target delay scale factor. on impossible diffi" +
            "culty", typeof(Single))]
        public Single ImpossNewTargetDelay;
        [Abide.Guerilla.Tags.FieldAttribute("easy burst separation#delay time between bursts scale factor for enemies. on easy" +
            " difficulty", typeof(Single))]
        public Single EasyBurstSeparation;
        [Abide.Guerilla.Tags.FieldAttribute("normal burst separation#delay time between bursts scale factor for enemies. on no" +
            "rmal difficulty", typeof(Single))]
        public Single NormalBurstSeparation;
        [Abide.Guerilla.Tags.FieldAttribute("hard burst separation#delay time between bursts scale factor for enemies. on hard" +
            " difficulty", typeof(Single))]
        public Single HardBurstSeparation;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. burst separation#delay time between bursts scale factor for enemies. on i" +
            "mpossible difficulty", typeof(Single))]
        public Single ImpossBurstSeparation;
        [Abide.Guerilla.Tags.FieldAttribute("easy target tracking#additional target tracking fraction for enemies. on easy dif" +
            "ficulty", typeof(Single))]
        public Single EasyTargetTracking;
        [Abide.Guerilla.Tags.FieldAttribute("normal target tracking#additional target tracking fraction for enemies. on normal" +
            " difficulty", typeof(Single))]
        public Single NormalTargetTracking;
        [Abide.Guerilla.Tags.FieldAttribute("hard target tracking#additional target tracking fraction for enemies. on hard dif" +
            "ficulty", typeof(Single))]
        public Single HardTargetTracking;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. target tracking#additional target tracking fraction for enemies. on impos" +
            "sible difficulty", typeof(Single))]
        public Single ImpossTargetTracking;
        [Abide.Guerilla.Tags.FieldAttribute("easy target leading#additional target leading fraction for enemies. on easy diffi" +
            "culty", typeof(Single))]
        public Single EasyTargetLeading;
        [Abide.Guerilla.Tags.FieldAttribute("normal target leading#additional target leading fraction for enemies. on normal d" +
            "ifficulty", typeof(Single))]
        public Single NormalTargetLeading;
        [Abide.Guerilla.Tags.FieldAttribute("hard target leading#additional target leading fraction for enemies. on hard diffi" +
            "culty", typeof(Single))]
        public Single HardTargetLeading;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. target leading#additional target leading fraction for enemies. on impossi" +
            "ble difficulty", typeof(Single))]
        public Single ImpossTargetLeading;
        [Abide.Guerilla.Tags.FieldAttribute("easy overcharge chance#overcharge chance scale factor for enemies. on easy diffic" +
            "ulty", typeof(Single))]
        public Single EasyOverchargeChance;
        [Abide.Guerilla.Tags.FieldAttribute("normal overcharge chance#overcharge chance scale factor for enemies. on normal di" +
            "fficulty", typeof(Single))]
        public Single NormalOverchargeChance;
        [Abide.Guerilla.Tags.FieldAttribute("hard overcharge chance#overcharge chance scale factor for enemies. on hard diffic" +
            "ulty", typeof(Single))]
        public Single HardOverchargeChance;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. overcharge chance#overcharge chance scale factor for enemies. on impossib" +
            "le difficulty", typeof(Single))]
        public Single ImpossOverchargeChance;
        [Abide.Guerilla.Tags.FieldAttribute("easy special fire delay#delay between special-fire shots (overcharge, banshee bom" +
            "bs) scale factor for enemies. on easy difficulty", typeof(Single))]
        public Single EasySpecialFireDelay;
        [Abide.Guerilla.Tags.FieldAttribute("normal special fire delay#delay between special-fire shots (overcharge, banshee b" +
            "ombs) scale factor for enemies. on normal difficulty", typeof(Single))]
        public Single NormalSpecialFireDelay;
        [Abide.Guerilla.Tags.FieldAttribute("hard special fire delay#delay between special-fire shots (overcharge, banshee bom" +
            "bs) scale factor for enemies. on hard difficulty", typeof(Single))]
        public Single HardSpecialFireDelay;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. special fire delay#delay between special-fire shots (overcharge, banshee " +
            "bombs) scale factor for enemies. on impossible difficulty", typeof(Single))]
        public Single ImpossSpecialFireDelay;
        [Abide.Guerilla.Tags.FieldAttribute("easy guidance vs player#guidance velocity scale factor for all projectiles target" +
            "ed on a player. on easy difficulty", typeof(Single))]
        public Single EasyGuidanceVsPlayer;
        [Abide.Guerilla.Tags.FieldAttribute("normal guidance vs player#guidance velocity scale factor for all projectiles targ" +
            "eted on a player. on normal difficulty", typeof(Single))]
        public Single NormalGuidanceVsPlayer;
        [Abide.Guerilla.Tags.FieldAttribute("hard guidance vs player#guidance velocity scale factor for all projectiles target" +
            "ed on a player. on hard difficulty", typeof(Single))]
        public Single HardGuidanceVsPlayer;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. guidance vs player#guidance velocity scale factor for all projectiles tar" +
            "geted on a player. on impossible difficulty", typeof(Single))]
        public Single ImpossGuidanceVsPlayer;
        [Abide.Guerilla.Tags.FieldAttribute("easy melee delay base#delay period added to all melee attacks, even when berserk." +
            " on easy difficulty", typeof(Single))]
        public Single EasyMeleeDelayBase;
        [Abide.Guerilla.Tags.FieldAttribute("normal melee delay base#delay period added to all melee attacks, even when berser" +
            "k. on normal difficulty", typeof(Single))]
        public Single NormalMeleeDelayBase;
        [Abide.Guerilla.Tags.FieldAttribute("hard melee delay base#delay period added to all melee attacks, even when berserk." +
            " on hard difficulty", typeof(Single))]
        public Single HardMeleeDelayBase;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. melee delay base#delay period added to all melee attacks, even when berse" +
            "rk. on impossible difficulty", typeof(Single))]
        public Single ImpossMeleeDelayBase;
        [Abide.Guerilla.Tags.FieldAttribute("easy melee delay scale#multiplier for all existing non-berserk melee delay times." +
            " on easy difficulty", typeof(Single))]
        public Single EasyMeleeDelayScale;
        [Abide.Guerilla.Tags.FieldAttribute("normal melee delay scale#multiplier for all existing non-berserk melee delay time" +
            "s. on normal difficulty", typeof(Single))]
        public Single NormalMeleeDelayScale;
        [Abide.Guerilla.Tags.FieldAttribute("hard melee delay scale#multiplier for all existing non-berserk melee delay times." +
            " on hard difficulty", typeof(Single))]
        public Single HardMeleeDelayScale;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. melee delay scale#multiplier for all existing non-berserk melee delay tim" +
            "es. on impossible difficulty", typeof(Single))]
        public Single ImpossMeleeDelayScale;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("easy grenade chance scale#scale factor affecting the desicions to throw a grenade" +
            ". on easy difficulty", typeof(Single))]
        public Single EasyGrenadeChanceScale;
        [Abide.Guerilla.Tags.FieldAttribute("normal grenade chance scale#scale factor affecting the desicions to throw a grena" +
            "de. on normal difficulty", typeof(Single))]
        public Single NormalGrenadeChanceScale;
        [Abide.Guerilla.Tags.FieldAttribute("hard grenade chance scale#scale factor affecting the desicions to throw a grenade" +
            ". on hard difficulty", typeof(Single))]
        public Single HardGrenadeChanceScale;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. grenade chance scale#scale factor affecting the desicions to throw a gren" +
            "ade. on impossible difficulty", typeof(Single))]
        public Single ImpossGrenadeChanceScale;
        [Abide.Guerilla.Tags.FieldAttribute("easy grenade timer scale#scale factor affecting the delay period between grenades" +
            " thrown from the same encounter (lower is more often). on easy difficulty", typeof(Single))]
        public Single EasyGrenadeTimerScale;
        [Abide.Guerilla.Tags.FieldAttribute("normal grenade timer scale#scale factor affecting the delay period between grenad" +
            "es thrown from the same encounter (lower is more often). on normal difficulty", typeof(Single))]
        public Single NormalGrenadeTimerScale;
        [Abide.Guerilla.Tags.FieldAttribute("hard grenade timer scale#scale factor affecting the delay period between grenades" +
            " thrown from the same encounter (lower is more often). on hard difficulty", typeof(Single))]
        public Single HardGrenadeTimerScale;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. grenade timer scale#scale factor affecting the delay period between grena" +
            "des thrown from the same encounter (lower is more often). on impossible difficul" +
            "ty", typeof(Single))]
        public Single ImpossGrenadeTimerScale;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("easy major upgrade (normal)#fraction of actors upgraded to their major variant. o" +
            "n easy difficulty", typeof(Single))]
        public Single EasyMajorUpgradeNormal;
        [Abide.Guerilla.Tags.FieldAttribute("normal major upgrade (normal)#fraction of actors upgraded to their major variant." +
            " on normal difficulty", typeof(Single))]
        public Single NormalMajorUpgradeNormal;
        [Abide.Guerilla.Tags.FieldAttribute("hard major upgrade (normal)#fraction of actors upgraded to their major variant. o" +
            "n hard difficulty", typeof(Single))]
        public Single HardMajorUpgradeNormal;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. major upgrade (normal)#fraction of actors upgraded to their major variant" +
            ". on impossible difficulty", typeof(Single))]
        public Single ImpossMajorUpgradeNormal;
        [Abide.Guerilla.Tags.FieldAttribute("easy major upgrade (few)#fraction of actors upgraded to their major variant when " +
            "mix = normal. on easy difficulty", typeof(Single))]
        public Single EasyMajorUpgradeFew;
        [Abide.Guerilla.Tags.FieldAttribute("normal major upgrade (few)#fraction of actors upgraded to their major variant whe" +
            "n mix = normal. on normal difficulty", typeof(Single))]
        public Single NormalMajorUpgradeFew;
        [Abide.Guerilla.Tags.FieldAttribute("hard major upgrade (few)#fraction of actors upgraded to their major variant when " +
            "mix = normal. on hard difficulty", typeof(Single))]
        public Single HardMajorUpgradeFew;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. major upgrade (few)#fraction of actors upgraded to their major variant wh" +
            "en mix = normal. on impossible difficulty", typeof(Single))]
        public Single ImpossMajorUpgradeFew;
        [Abide.Guerilla.Tags.FieldAttribute("easy major upgrade (many)#fraction of actors upgraded to their major variant when" +
            " mix = many. on easy difficulty", typeof(Single))]
        public Single EasyMajorUpgradeMany;
        [Abide.Guerilla.Tags.FieldAttribute("normal major upgrade (many)#fraction of actors upgraded to their major variant wh" +
            "en mix = many. on normal difficulty", typeof(Single))]
        public Single NormalMajorUpgradeMany;
        [Abide.Guerilla.Tags.FieldAttribute("hard major upgrade (many)#fraction of actors upgraded to their major variant when" +
            " mix = many. on hard difficulty", typeof(Single))]
        public Single HardMajorUpgradeMany;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. major upgrade (many)#fraction of actors upgraded to their major variant w" +
            "hen mix = many. on impossible difficulty", typeof(Single))]
        public Single ImpossMajorUpgradeMany;
        [Abide.Guerilla.Tags.FieldAttribute("easy player vehicle ram chance#Chance of deciding to ram the player in a vehicle " +
            "on easy difficulty", typeof(Single))]
        public Single EasyPlayerVehicleRamChance;
        [Abide.Guerilla.Tags.FieldAttribute("normal player vehicle ram chance#Chance of deciding to ram the player in a vehicl" +
            "e on normal difficulty", typeof(Single))]
        public Single NormalPlayerVehicleRamChance;
        [Abide.Guerilla.Tags.FieldAttribute("hard player vehicle ram chance#Chance of deciding to ram the player in a vehicle " +
            "on hard difficulty", typeof(Single))]
        public Single HardPlayerVehicleRamChance;
        [Abide.Guerilla.Tags.FieldAttribute("imposs. player vehicle ram chance#Chance of deciding to ram the player in a vehic" +
            "le on impossible difficulty", typeof(Single))]
        public Single ImpossPlayerVehicleRamChance;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString7;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(84)]
        public Byte[] EmptyString8;
    }
}
#pragma warning restore CS1591
