#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class DynamicSpawnZoneOverloadBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Overload Type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(OverloadTypeOptions), false)]
        public Int16 OverloadType;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Inner Radius", typeof(Single))]
        public Single InnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("Outer Radius", typeof(Single))]
        public Single OuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("Weight", typeof(Single))]
        public Single Weight;
        public enum OverloadTypeOptions
        {
            Enemy = 0,
            Friend = 1,
            EnemyVehicle = 2,
            FriendlyVehicle = 3,
            EmptyVehicle = 4,
            OddballInclusion = 5,
            OddballExclusion = 6,
            HillInclusion = 7,
            HillExclusion = 8,
            LastRaceFlag = 9,
            DeadAlly = 10,
            ControlledTerritory = 11,
        }
    }
}
#pragma warning restore CS1591
