#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(76, 4)]
    public class FrictionPointDefinitionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("marker name^", typeof(StringId))]
        public StringId MarkerName;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("fraction of total mass#(0.0-1.0) fraction of total vehicle mass", typeof(Single))]
        public Single FractionOfTotalMass;
        [Abide.Guerilla.Tags.FieldAttribute("radius", typeof(Single))]
        public Single Radius;
        [Abide.Guerilla.Tags.FieldAttribute("damaged radius#radius when the tire is blown off.", typeof(Single))]
        public Single DamagedRadius;
        [Abide.Guerilla.Tags.FieldAttribute("friction type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FrictionTypeOptions), false)]
        public Int16 FrictionType;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("moving friction velocity diff", typeof(Single))]
        public Single MovingFrictionVelocityDiff;
        [Abide.Guerilla.Tags.FieldAttribute("e-brake moving friction", typeof(Single))]
        public Single EbrakeMovingFriction;
        [Abide.Guerilla.Tags.FieldAttribute("e-brake friction", typeof(Single))]
        public Single EbrakeFriction;
        [Abide.Guerilla.Tags.FieldAttribute("e-brake moving friction vel diff", typeof(Single))]
        public Single EbrakeMovingFrictionVelDiff;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(20)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("collision global material name", typeof(StringId))]
        public StringId CollisionGlobalMaterialName;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("model state destroyed#only need point can destroy flag set", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ModelStateDestroyed), false)]
        public Int16 ModelStateDestroyed1;
        [Abide.Guerilla.Tags.FieldAttribute("region name#only need point can destroy flag set", typeof(StringId))]
        public StringId RegionName;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString3;
        public enum FlagsOptions
        {
            GetsDamageFromRegion = 1,
            Powered = 2,
            FrontTurning = 4,
            RearTurning = 8,
            AttachedToEbrake = 16,
            CanBeDestroyed = 32,
        }
        public enum FrictionTypeOptions
        {
            Point = 0,
            Forward = 1,
        }
        public enum ModelStateDestroyed
        {
            Default = 0,
            MinorDamage = 1,
            MediumDamage = 2,
            MajorDamage = 3,
            Destroyed = 4,
        }
    }
}
#pragma warning restore CS1591
