#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(24, 4)]
    public class GloalWindPrimitivesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("position", typeof(Vector3))]
        public Vector3 Position;
        [Abide.Guerilla.Tags.FieldAttribute("radius", typeof(Single))]
        public Single Radius;
        [Abide.Guerilla.Tags.FieldAttribute("strength", typeof(Single))]
        public Single Strength;
        [Abide.Guerilla.Tags.FieldAttribute("wind primitive type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(WindPrimitiveTypeOptions), false)]
        public Int16 WindPrimitiveType;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        public enum WindPrimitiveTypeOptions
        {
            Vortex = 0,
            Gust = 1,
            Implosion = 2,
            Explosion = 3,
        }
    }
}
#pragma warning restore CS1591
