#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(680, 4)]
    public class GlobalErrorReportCategoriesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name^*", typeof(String256))]
        public String256 Name;
        [Abide.Guerilla.Tags.FieldAttribute("Report Type*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ReportType), false)]
        public Int16 ReportType1;
        [Abide.Guerilla.Tags.FieldAttribute("Flags*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(Flags), true)]
        public Int16 Flags1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(404)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("Reports*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Error Report", 1024, typeof(ErrorReportsBlock))]
        public TagBlock Reports;
        public enum ReportType
        {
            Silent = 0,
            Comment = 1,
            Warning = 2,
            Error = 3,
        }
        public enum Flags
        {
            Rendered = 1,
            TangentSpace = 2,
            Noncritical = 4,
            LightmapLight = 8,
            ReportKeyIsValid = 16,
        }
    }
}
#pragma warning restore CS1591
