#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    public class GlobalLeafConnectionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("plane index*", typeof(Int32))]
        public Int32 PlaneIndex;
        [Abide.Guerilla.Tags.FieldAttribute("back leaf index*", typeof(Int32))]
        public Int32 BackLeafIndex;
        [Abide.Guerilla.Tags.FieldAttribute("front leaf index*", typeof(Int32))]
        public Int32 FrontLeafIndex;
        [Abide.Guerilla.Tags.FieldAttribute("vertices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Leaf Connection Vertex Block", 64, typeof(LeafConnectionVertexBlock))]
        public TagBlock Vertices;
        [Abide.Guerilla.Tags.FieldAttribute("area*", typeof(Single))]
        public Single Area;
    }
}
#pragma warning restore CS1591
