#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(56, 4)]
    public class GlobalGeometryPointDataStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Raw Points*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Point", 32767, typeof(GlobalGeometryRawPointBlock))]
        public TagBlock RawPoints;
        [Abide.Guerilla.Tags.FieldAttribute("Runtime Point Data*", typeof(Byte[]))]
        public Byte[] RuntimePointData;
        [Abide.Guerilla.Tags.FieldAttribute("Rigid Point Groups*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Rigid Point Group", 32767, typeof(GlobalGeometryRigidPointGroupBlock))]
        public TagBlock RigidPointGroups;
        [Abide.Guerilla.Tags.FieldAttribute("Vertex-Point Indices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Index", 32767, typeof(GlobalGeometryPointDataIndexBlock))]
        public TagBlock VertexpointIndices;
    }
}
#pragma warning restore CS1591
