#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(68, 4)]
    public class GlobalScenarioLoadParametersBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("scenario^", typeof(TagReference))]
        public TagReference Scenario;
        [Abide.Guerilla.Tags.FieldAttribute("parameters", typeof(Byte[]))]
        public Byte[] Parameters;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString;
    }
}
#pragma warning restore CS1591
