#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(40, 4)]
    public class HsScriptsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name^*", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("script type*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ScriptType), false)]
        public Int16 ScriptType1;
        [Abide.Guerilla.Tags.FieldAttribute("return type*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ReturnType), false)]
        public Int16 ReturnType1;
        [Abide.Guerilla.Tags.FieldAttribute("root expression index*", typeof(Int32))]
        public Int32 RootExpressionIndex;
        public enum ScriptType
        {
            Startup = 0,
            Dormant = 1,
            Continuous = 2,
            Static = 3,
            Stub = 4,
            CommandScript = 5,
        }
        public enum ReturnType
        {
            Unparsed = 0,
            SpecialForm = 1,
            FunctionName = 2,
            Passthrough = 3,
            Void = 4,
            Boolean = 5,
            Real = 6,
            Short = 7,
            Long = 8,
            String = 9,
            Script = 10,
            StringId = 11,
            UnitSeatMapping = 12,
            TriggerVolume = 13,
            CutsceneFlag = 14,
            CutsceneCameraPoint = 15,
            CutsceneTitle = 16,
            CutsceneRecording = 17,
            DeviceGroup = 18,
            Ai = 19,
            AiCommandList = 20,
            AiCommandScript = 21,
            AiBehavior = 22,
            AiOrders = 23,
            StartingProfile = 24,
            Conversation = 25,
            StructureBsp = 26,
            Navpoint = 27,
            PointReference = 28,
            Style = 29,
            HudMessage = 30,
            ObjectList = 31,
            Sound = 32,
            Effect = 33,
            Damage = 34,
            LoopingSound = 35,
            AnimationGraph = 36,
            DamageEffect = 37,
            ObjectDefinition = 38,
            Bitmap = 39,
            Shader = 40,
            RenderModel = 41,
            StructureDefinition = 42,
            LightmapDefinition = 43,
            GameDifficulty = 44,
            Team = 45,
            ActorType = 46,
            HudCorner = 47,
            ModelState = 48,
            NetworkEvent = 49,
            Object = 50,
            Unit = 51,
            Vehicle = 52,
            Weapon = 53,
            Device = 54,
            Scenery = 55,
            ObjectName = 56,
            UnitName = 57,
            VehicleName = 58,
            WeaponName = 59,
            DeviceName = 60,
            SceneryName = 61,
        }
    }
}
#pragma warning restore CS1591
