#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(52, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("scenario_hs_source_file", "hsc*", "����", typeof(HsSourceFilesBlock))]
    public class HsSourceFilesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name*", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("source*", typeof(Byte[]))]
        public Byte[] Source;
    }
}
#pragma warning restore CS1591
