#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(1364, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("hud_globals", "hudg", "����", typeof(HudGlobalsBlock))]
    public class HudGlobalsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("anchor", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(AnchorOptions), false)]
        public Int16 Anchor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("anchor offset", typeof(Vector2))]
        public Vector2 AnchorOffset;
        [Abide.Guerilla.Tags.FieldAttribute("width scale", typeof(Single))]
        public Single WidthScale;
        [Abide.Guerilla.Tags.FieldAttribute("height scale", typeof(Single))]
        public Single HeightScale;
        [Abide.Guerilla.Tags.FieldAttribute("scaling flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ScalingFlagsOptions), true)]
        public Int16 ScalingFlags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(20)]
        public Byte[] EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("obsolete1", typeof(TagReference))]
        public TagReference Obsolete1;
        [Abide.Guerilla.Tags.FieldAttribute("obsolete2", typeof(TagReference))]
        public TagReference Obsolete2;
        [Abide.Guerilla.Tags.FieldAttribute("up time", typeof(Single))]
        public Single UpTime;
        [Abide.Guerilla.Tags.FieldAttribute("fade time", typeof(Single))]
        public Single FadeTime;
        [Abide.Guerilla.Tags.FieldAttribute("icon color", typeof(ColorArgbF))]
        public ColorArgbF IconColor;
        [Abide.Guerilla.Tags.FieldAttribute("text color", typeof(ColorArgbF))]
        public ColorArgbF TextColor;
        [Abide.Guerilla.Tags.FieldAttribute("text spacing", typeof(Single))]
        public Single TextSpacing;
        [Abide.Guerilla.Tags.FieldAttribute("item message text", typeof(TagReference))]
        public TagReference ItemMessageText;
        [Abide.Guerilla.Tags.FieldAttribute("icon bitmap", typeof(TagReference))]
        public TagReference IconBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("alternate icon text", typeof(TagReference))]
        public TagReference AlternateIconText;
        [Abide.Guerilla.Tags.FieldAttribute("button icons", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Hud Button Icon Block", 18, typeof(HudButtonIconBlock))]
        public TagBlock ButtonIcons;
        [Abide.Guerilla.Tags.FieldAttribute("default color", typeof(ColorArgb))]
        public ColorArgb DefaultColor;
        [Abide.Guerilla.Tags.FieldAttribute("flashing color", typeof(ColorArgb))]
        public ColorArgb FlashingColor;
        [Abide.Guerilla.Tags.FieldAttribute("flash period", typeof(Single))]
        public Single FlashPeriod;
        [Abide.Guerilla.Tags.FieldAttribute("flash delay#time between flashes", typeof(Single))]
        public Single FlashDelay;
        [Abide.Guerilla.Tags.FieldAttribute("number of flashes", typeof(Int16))]
        public Int16 NumberOfFlashes;
        [Abide.Guerilla.Tags.FieldAttribute("flash flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlashFlagsOptions), true)]
        public Int16 FlashFlags;
        [Abide.Guerilla.Tags.FieldAttribute("flash length#time of each flash", typeof(Single))]
        public Single FlashLength;
        [Abide.Guerilla.Tags.FieldAttribute("disabled color", typeof(ColorArgb))]
        public ColorArgb DisabledColor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("hud messages", typeof(TagReference))]
        public TagReference HudMessages;
        [Abide.Guerilla.Tags.FieldAttribute("default color", typeof(ColorArgb))]
        public ColorArgb DefaultColor1;
        [Abide.Guerilla.Tags.FieldAttribute("flashing color", typeof(ColorArgb))]
        public ColorArgb FlashingColor1;
        [Abide.Guerilla.Tags.FieldAttribute("flash period", typeof(Single))]
        public Single FlashPeriod1;
        [Abide.Guerilla.Tags.FieldAttribute("flash delay#time between flashes", typeof(Single))]
        public Single FlashDelay1;
        [Abide.Guerilla.Tags.FieldAttribute("number of flashes", typeof(Int16))]
        public Int16 NumberOfFlashes1;
        [Abide.Guerilla.Tags.FieldAttribute("flash flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlashFlagsOptions1), true)]
        public Int16 FlashFlags1;
        [Abide.Guerilla.Tags.FieldAttribute("flash length#time of each flash", typeof(Single))]
        public Single FlashLength1;
        [Abide.Guerilla.Tags.FieldAttribute("disabled color", typeof(ColorArgb))]
        public ColorArgb DisabledColor1;
        [Abide.Guerilla.Tags.FieldAttribute("uptime ticks", typeof(Int16))]
        public Int16 UptimeTicks;
        [Abide.Guerilla.Tags.FieldAttribute("fade ticks", typeof(Int16))]
        public Int16 FadeTicks;
        [Abide.Guerilla.Tags.FieldAttribute("top offset", typeof(Single))]
        public Single TopOffset;
        [Abide.Guerilla.Tags.FieldAttribute("bottom offset", typeof(Single))]
        public Single BottomOffset;
        [Abide.Guerilla.Tags.FieldAttribute("left offset", typeof(Single))]
        public Single LeftOffset;
        [Abide.Guerilla.Tags.FieldAttribute("right offset", typeof(Single))]
        public Single RightOffset;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("arrow bitmap", typeof(TagReference))]
        public TagReference ArrowBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("waypoint arrows", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Hud Waypoint Arrow Block", 16, typeof(HudWaypointArrowBlock))]
        public TagBlock WaypointArrows;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(80)]
        public Byte[] EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("hud scale in multiplayer", typeof(Single))]
        public Single HudScaleInMultiplayer;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(256)]
        public Byte[] EmptyString7;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString8;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor range", typeof(Single))]
        public Single MotionSensorRange;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor velocity sensitivity#how fast something moves to show up on the mot" +
            "ion sensor", typeof(Single))]
        public Single MotionSensorVelocitySensitivity;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor scale [DON\'T TOUCH EVER]*", typeof(Single))]
        public Single MotionSensorScaleDontTouchEver;
        [Abide.Guerilla.Tags.FieldAttribute("default chapter title bounds", typeof(Vector2))]
        public Vector2 DefaultChapterTitleBounds;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(44)]
        public Byte[] EmptyString9;
        [Abide.Guerilla.Tags.FieldAttribute("top offset", typeof(Int16))]
        public Int16 TopOffset1;
        [Abide.Guerilla.Tags.FieldAttribute("bottom offset", typeof(Int16))]
        public Int16 BottomOffset1;
        [Abide.Guerilla.Tags.FieldAttribute("left offset", typeof(Int16))]
        public Int16 LeftOffset1;
        [Abide.Guerilla.Tags.FieldAttribute("right offset", typeof(Int16))]
        public Int16 RightOffset1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString10;
        [Abide.Guerilla.Tags.FieldAttribute("indicator bitmap", typeof(TagReference))]
        public TagReference IndicatorBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("sequence index", typeof(Int16))]
        public Int16 SequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("multiplayer sequence index", typeof(Int16))]
        public Int16 MultiplayerSequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("color", typeof(ColorArgb))]
        public ColorArgb Color;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString11;
        [Abide.Guerilla.Tags.FieldAttribute("default color", typeof(ColorArgb))]
        public ColorArgb DefaultColor2;
        [Abide.Guerilla.Tags.FieldAttribute("flashing color", typeof(ColorArgb))]
        public ColorArgb FlashingColor2;
        [Abide.Guerilla.Tags.FieldAttribute("flash period", typeof(Single))]
        public Single FlashPeriod2;
        [Abide.Guerilla.Tags.FieldAttribute("flash delay#time between flashes", typeof(Single))]
        public Single FlashDelay2;
        [Abide.Guerilla.Tags.FieldAttribute("number of flashes", typeof(Int16))]
        public Int16 NumberOfFlashes2;
        [Abide.Guerilla.Tags.FieldAttribute("flash flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlashFlagsOptions2), true)]
        public Int16 FlashFlags2;
        [Abide.Guerilla.Tags.FieldAttribute("flash length#time of each flash", typeof(Single))]
        public Single FlashLength2;
        [Abide.Guerilla.Tags.FieldAttribute("disabled color", typeof(ColorArgb))]
        public ColorArgb DisabledColor2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString12;
        [Abide.Guerilla.Tags.FieldAttribute("default color", typeof(ColorArgb))]
        public ColorArgb DefaultColor3;
        [Abide.Guerilla.Tags.FieldAttribute("flashing color", typeof(ColorArgb))]
        public ColorArgb FlashingColor3;
        [Abide.Guerilla.Tags.FieldAttribute("flash period", typeof(Single))]
        public Single FlashPeriod3;
        [Abide.Guerilla.Tags.FieldAttribute("flash delay#time between flashes", typeof(Single))]
        public Single FlashDelay3;
        [Abide.Guerilla.Tags.FieldAttribute("number of flashes", typeof(Int16))]
        public Int16 NumberOfFlashes3;
        [Abide.Guerilla.Tags.FieldAttribute("flash flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlashFlagsOptions3), true)]
        public Int16 FlashFlags3;
        [Abide.Guerilla.Tags.FieldAttribute("flash length#time of each flash", typeof(Single))]
        public Single FlashLength3;
        [Abide.Guerilla.Tags.FieldAttribute("disabled color", typeof(ColorArgb))]
        public ColorArgb DisabledColor3;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString13;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(40)]
        public Byte[] EmptyString14;
        [Abide.Guerilla.Tags.FieldAttribute("carnage report bitmap", typeof(TagReference))]
        public TagReference CarnageReportBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("loading begin text", typeof(Int16))]
        public Int16 LoadingBeginText;
        [Abide.Guerilla.Tags.FieldAttribute("loading end text", typeof(Int16))]
        public Int16 LoadingEndText;
        [Abide.Guerilla.Tags.FieldAttribute("checkpoint begin text", typeof(Int16))]
        public Int16 CheckpointBeginText;
        [Abide.Guerilla.Tags.FieldAttribute("checkpoint end text", typeof(Int16))]
        public Int16 CheckpointEndText;
        [Abide.Guerilla.Tags.FieldAttribute("checkpoint sound", typeof(TagReference))]
        public TagReference CheckpointSound;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(96)]
        public Byte[] EmptyString15;
        [Abide.Guerilla.Tags.FieldAttribute("new globals", typeof(GlobalNewHudGlobalsStructBlock))]
        public GlobalNewHudGlobalsStructBlock NewGlobals;
        public enum AnchorOptions
        {
            TopLeft = 0,
            TopRight = 1,
            BottomLeft = 2,
            BottomRight = 3,
            Center = 4,
            Crosshair = 5,
        }
        public enum ScalingFlagsOptions
        {
            DontScaleOffset = 1,
            DontScaleSize = 2,
        }
        public enum FlashFlagsOptions
        {
            ReverseDefaultflashingColors = 1,
        }
        public enum FlashFlagsOptions1
        {
            ReverseDefaultflashingColors = 1,
        }
        public enum FlashFlagsOptions2
        {
            ReverseDefaultflashingColors = 1,
        }
        public enum FlashFlagsOptions3
        {
            ReverseDefaultflashingColors = 1,
        }
    }
}
#pragma warning restore CS1591
