#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(48, 4)]
    public class InheritedAnimationBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("inherited graph*", typeof(TagReference))]
        public TagReference InheritedGraph;
        [Abide.Guerilla.Tags.FieldAttribute("node map*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Inherited Animation Node Map Block", 255, typeof(InheritedAnimationNodeMapBlock))]
        public TagBlock NodeMap;
        [Abide.Guerilla.Tags.FieldAttribute("node map flags*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Inherited Animation Node Map Flag Block", 255, typeof(InheritedAnimationNodeMapFlagBlock))]
        public TagBlock NodeMapFlags;
        [Abide.Guerilla.Tags.FieldAttribute("root z offset*", typeof(Single))]
        public Single RootZOffset;
        [Abide.Guerilla.Tags.FieldAttribute("inheritance_flags*", typeof(Int32))]
        public Int32 InheritanceFlags;
    }
}
#pragma warning restore CS1591
