#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(304, 4)]
    public class InterfaceTagReferences
    {
        [Abide.Guerilla.Tags.FieldAttribute("obsolete1", typeof(TagReference))]
        public TagReference Obsolete1;
        [Abide.Guerilla.Tags.FieldAttribute("obsolete2", typeof(TagReference))]
        public TagReference Obsolete2;
        [Abide.Guerilla.Tags.FieldAttribute("screen color table", typeof(TagReference))]
        public TagReference ScreenColorTable;
        [Abide.Guerilla.Tags.FieldAttribute("hud color table", typeof(TagReference))]
        public TagReference HudColorTable;
        [Abide.Guerilla.Tags.FieldAttribute("editor color table", typeof(TagReference))]
        public TagReference EditorColorTable;
        [Abide.Guerilla.Tags.FieldAttribute("dialog color table", typeof(TagReference))]
        public TagReference DialogColorTable;
        [Abide.Guerilla.Tags.FieldAttribute("hud globals", typeof(TagReference))]
        public TagReference HudGlobals;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor sweep bitmap", typeof(TagReference))]
        public TagReference MotionSensorSweepBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor sweep bitmap mask", typeof(TagReference))]
        public TagReference MotionSensorSweepBitmapMask;
        [Abide.Guerilla.Tags.FieldAttribute("multiplayer hud bitmap", typeof(TagReference))]
        public TagReference MultiplayerHudBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("hud digits definition", typeof(TagReference))]
        public TagReference HudDigitsDefinition;
        [Abide.Guerilla.Tags.FieldAttribute("motion sensor blip bitmap", typeof(TagReference))]
        public TagReference MotionSensorBlipBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("interface goo map1", typeof(TagReference))]
        public TagReference InterfaceGooMap1;
        [Abide.Guerilla.Tags.FieldAttribute("interface goo map2", typeof(TagReference))]
        public TagReference InterfaceGooMap2;
        [Abide.Guerilla.Tags.FieldAttribute("interface goo map3", typeof(TagReference))]
        public TagReference InterfaceGooMap3;
        [Abide.Guerilla.Tags.FieldAttribute("mainmenu ui globals", typeof(TagReference))]
        public TagReference MainmenuUiGlobals;
        [Abide.Guerilla.Tags.FieldAttribute("singleplayer ui globals", typeof(TagReference))]
        public TagReference SingleplayerUiGlobals;
        [Abide.Guerilla.Tags.FieldAttribute("multiplayer ui globals", typeof(TagReference))]
        public TagReference MultiplayerUiGlobals;
    }
}
#pragma warning restore CS1591
