#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(132, 4)]
    public class LimitedHingeConstraintsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("constraint bodies*", typeof(ConstraintBodiesStructBlock))]
        public ConstraintBodiesStructBlock ConstraintBodies;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("limit friction*", typeof(Single))]
        public Single LimitFriction;
        [Abide.Guerilla.Tags.FieldAttribute("limit min angle*", typeof(Single))]
        public Single LimitMinAngle;
        [Abide.Guerilla.Tags.FieldAttribute("limit max angle*", typeof(Single))]
        public Single LimitMaxAngle;
    }
}
#pragma warning restore CS1591
