#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(276, 4)]
    public class LiquidArcBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("sprite count", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(SpriteCountOptions), false)]
        public Int16 SpriteCount;
        [Abide.Guerilla.Tags.FieldAttribute("natural length:world units", typeof(Single))]
        public Single NaturalLength;
        [Abide.Guerilla.Tags.FieldAttribute("instances", typeof(Int16))]
        public Int16 Instances;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("instance spread angle:degrees", typeof(Single))]
        public Single InstanceSpreadAngle;
        [Abide.Guerilla.Tags.FieldAttribute("instance rotation period:seconds", typeof(Single))]
        public Single InstanceRotationPeriod;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("material effects", typeof(TagReference))]
        public TagReference MaterialEffects;
        [Abide.Guerilla.Tags.FieldAttribute("bitmap", typeof(TagReference))]
        public TagReference Bitmap;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("horizontal range", typeof(ScalarFunctionStructBlock))]
        public ScalarFunctionStructBlock HorizontalRange1;
        [Abide.Guerilla.Tags.FieldAttribute("vertical range", typeof(ScalarFunctionStructBlock))]
        public ScalarFunctionStructBlock VerticalRange1;
        [Abide.Guerilla.Tags.FieldAttribute("vertical negative scale:[0,1]", typeof(Single))]
        public Single VerticalNegativeScale;
        [Abide.Guerilla.Tags.FieldAttribute("roughness", typeof(ScalarFunctionStructBlock))]
        public ScalarFunctionStructBlock Roughness1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(64)]
        public Byte[] EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("octave 1 frequency:cycles/second", typeof(Single))]
        public Single Octave1Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 2 frequency:cycles/second", typeof(Single))]
        public Single Octave2Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 3 frequency:cycles/second", typeof(Single))]
        public Single Octave3Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 4 frequency:cycles/second", typeof(Single))]
        public Single Octave4Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 5 frequency:cycles/second", typeof(Single))]
        public Single Octave5Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 6 frequency:cycles/second", typeof(Single))]
        public Single Octave6Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 7 frequency:cycles/second", typeof(Single))]
        public Single Octave7Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 8 frequency:cycles/second", typeof(Single))]
        public Single Octave8Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("octave 9 frequency:cycles/second", typeof(Single))]
        public Single Octave9Frequency;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(28)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("octave flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(OctaveFlagsOptions), true)]
        public Int16 OctaveFlags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("cores", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Core", 4, typeof(LiquidCoreBlock))]
        public TagBlock Cores;
        [Abide.Guerilla.Tags.FieldAttribute("range-scale", typeof(ScalarFunctionStructBlock))]
        public ScalarFunctionStructBlock Rangescale;
        [Abide.Guerilla.Tags.FieldAttribute("brightness-scale", typeof(ScalarFunctionStructBlock))]
        public ScalarFunctionStructBlock Brightnessscale;
        public enum FlagsOptions
        {
            BasisMarkerrelative = 1,
            SpreadByExternalInput = 2,
            CollideWithStuff = 4,
            NoPerspectiveMidpoints = 8,
        }
        public enum SpriteCountOptions
        {
            _4Sprites = 0,
            _8Sprites = 1,
            _16Sprites = 2,
            _32Sprites = 3,
            _64Sprites = 4,
            _128Sprites = 5,
            _256Sprites = 6,
        }
        public enum OctaveFlagsOptions
        {
            Octave1 = 1,
            Octave2 = 2,
            Octave3 = 4,
            Octave4 = 8,
            Octave5 = 16,
            Octave6 = 32,
            Octave7 = 64,
            Octave8 = 128,
            Octave9 = 256,
        }
    }
}
#pragma warning restore CS1591
