#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class ListShapesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("shape type*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ShapeType), false)]
        public Int16 ShapeType1;
        [Abide.Guerilla.Tags.FieldAttribute("shape*", typeof(Int16))]
        public Int16 Shape;
        [Abide.Guerilla.Tags.FieldAttribute("collision filter*", typeof(Int32))]
        public Int32 CollisionFilter;
        public enum ShapeType
        {
            Sphere = 0,
            Pill = 1,
            Box = 2,
            Triangle = 3,
            Polyhedron = 4,
            MultiSphere = 5,
            Unused0 = 6,
            Unused1 = 7,
            Unused2 = 8,
            Unused3 = 9,
            Unused4 = 10,
            Unused5 = 11,
            Unused6 = 12,
            Unused7 = 13,
            List = 14,
            Mopp = 15,
        }
    }
}
#pragma warning restore CS1591
