#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(36, 4)]
    public class MaterialEffectBlockV2
    {
        [Abide.Guerilla.Tags.FieldAttribute("old materials (DO NOT USE)", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Old Material Effect Material Block", 33, typeof(OldMaterialEffectMaterialBlock))]
        public TagBlock OldMaterialsDoNotUse;
        [Abide.Guerilla.Tags.FieldAttribute("sounds", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Material Effect Material Block", 500, typeof(MaterialEffectMaterialBlock))]
        public TagBlock Sounds;
        [Abide.Guerilla.Tags.FieldAttribute("effects", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Material Effect Material Block", 500, typeof(MaterialEffectMaterialBlock))]
        public TagBlock Effects;
    }
}
#pragma warning restore CS1591
