#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class MaterialPhysicsPropertiesStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("friction", typeof(Single))]
        public Single Friction;
        [Abide.Guerilla.Tags.FieldAttribute("restitution", typeof(Single))]
        public Single Restitution;
        [Abide.Guerilla.Tags.FieldAttribute("density:kg/m^3", typeof(Single))]
        public Single Density;
    }
}
#pragma warning restore CS1591
