#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class ModelVariantStateBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("permutation name", typeof(StringId))]
        public StringId PermutationName;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(1)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("property flags", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(PropertyFlagsOptions), true)]
        public Byte PropertyFlags;
        [Abide.Guerilla.Tags.FieldAttribute("state^", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(State), false)]
        public Int16 State1;
        [Abide.Guerilla.Tags.FieldAttribute("looping effect#played while the model is in this state", typeof(TagReference))]
        public TagReference LoopingEffect;
        [Abide.Guerilla.Tags.FieldAttribute("looping effect marker name", typeof(StringId))]
        public StringId LoopingEffectMarkerName;
        [Abide.Guerilla.Tags.FieldAttribute("initial probability", typeof(Single))]
        public Single InitialProbability;
        public enum PropertyFlagsOptions
        {
            Blurred = 1,
            HellaBlurred = 2,
            Shielded = 4,
        }
        public enum State
        {
            Default = 0,
            MinorDamage = 1,
            MediumDamage = 2,
            MajorDamage = 3,
            Destroyed = 4,
        }
    }
}
#pragma warning restore CS1591
