#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    public class ModelTargetBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("marker name^#multiple markers become multiple spheres of the same radius", typeof(StringId))]
        public StringId MarkerName;
        [Abide.Guerilla.Tags.FieldAttribute("size#sphere radius", typeof(Single))]
        public Single Size;
        [Abide.Guerilla.Tags.FieldAttribute("cone angle#the target is only visible when viewed within this angle of the marker" +
            "\'s x axis", typeof(Single))]
        public Single ConeAngle;
        [Abide.Guerilla.Tags.FieldAttribute("damage section#the target is associated with this damage section", typeof(Int16))]
        public Int16 DamageSection;
        [Abide.Guerilla.Tags.FieldAttribute("variant#the target will only appear with this variant", typeof(Int16))]
        public Int16 Variant;
        [Abide.Guerilla.Tags.FieldAttribute("targeting relevance#higher relevances turn into stronger magnetisms", typeof(Single))]
        public Single TargetingRelevance;
        [Abide.Guerilla.Tags.FieldAttribute("lock-on data", typeof(ModelTargetLockOnDataStructBlock))]
        public ModelTargetLockOnDataStructBlock LockonData;
    }
}
#pragma warning restore CS1591
