#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("mouse_cursor_definition", "mcsr", "����", typeof(MouseCursorDefinitionBlock))]
    public class MouseCursorDefinitionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("mouse cursor bitmaps", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Mouse Cursor Bitmap Reference Block", 4, typeof(MouseCursorBitmapReferenceBlock))]
        public TagBlock MouseCursorBitmaps1;
        [Abide.Guerilla.Tags.FieldAttribute("animation speed (fps)", typeof(Single))]
        public Single AnimationSpeedFps;
    }
}
#pragma warning restore CS1591
