#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(60, 4)]
    public class MultiplayerUniversalBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("random player names", typeof(TagReference))]
        public TagReference RandomPlayerNames;
        [Abide.Guerilla.Tags.FieldAttribute("team names", typeof(TagReference))]
        public TagReference TeamNames;
        [Abide.Guerilla.Tags.FieldAttribute("team colors", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Multiplayer Color Block", 32, typeof(MultiplayerColorBlock))]
        public TagBlock TeamColors;
        [Abide.Guerilla.Tags.FieldAttribute("multiplayer text", typeof(TagReference))]
        public TagReference MultiplayerText;
    }
}
#pragma warning restore CS1591
