#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(1640, 4)]
    public class MultiplayerRuntimeBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flag", typeof(TagReference))]
        public TagReference Flag;
        [Abide.Guerilla.Tags.FieldAttribute("ball", typeof(TagReference))]
        public TagReference Ball;
        [Abide.Guerilla.Tags.FieldAttribute("unit", typeof(TagReference))]
        public TagReference Unit;
        [Abide.Guerilla.Tags.FieldAttribute("flag shader", typeof(TagReference))]
        public TagReference FlagShader;
        [Abide.Guerilla.Tags.FieldAttribute("hill shader", typeof(TagReference))]
        public TagReference HillShader;
        [Abide.Guerilla.Tags.FieldAttribute("head", typeof(TagReference))]
        public TagReference Head;
        [Abide.Guerilla.Tags.FieldAttribute("juggernaut powerup", typeof(TagReference))]
        public TagReference JuggernautPowerup;
        [Abide.Guerilla.Tags.FieldAttribute("da bomb", typeof(TagReference))]
        public TagReference DaBomb;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("weapons", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapons Block", 20, typeof(WeaponsBlock))]
        public TagBlock Weapons;
        [Abide.Guerilla.Tags.FieldAttribute("vehicles", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Vehicles Block", 20, typeof(VehiclesBlock))]
        public TagBlock Vehicles;
        [Abide.Guerilla.Tags.FieldAttribute("arr!", typeof(GrenadeAndPowerupStructBlock))]
        public GrenadeAndPowerupStructBlock Arr;
        [Abide.Guerilla.Tags.FieldAttribute("in game text", typeof(TagReference))]
        public TagReference InGameText;
        [Abide.Guerilla.Tags.FieldAttribute("sounds", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Sounds Block", 60, typeof(SoundsBlock))]
        public TagBlock Sounds;
        [Abide.Guerilla.Tags.FieldAttribute("general events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine General Event Block", 128, typeof(GameEngineGeneralEventBlock))]
        public TagBlock GeneralEvents;
        [Abide.Guerilla.Tags.FieldAttribute("flavor events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Flavor Event Block", 128, typeof(GameEngineFlavorEventBlock))]
        public TagBlock FlavorEvents;
        [Abide.Guerilla.Tags.FieldAttribute("slayer events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Slayer Event Block", 128, typeof(GameEngineSlayerEventBlock))]
        public TagBlock SlayerEvents;
        [Abide.Guerilla.Tags.FieldAttribute("ctf events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Ctf Event Block", 128, typeof(GameEngineCtfEventBlock))]
        public TagBlock CtfEvents;
        [Abide.Guerilla.Tags.FieldAttribute("oddball events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Oddball Event Block", 128, typeof(GameEngineOddballEventBlock))]
        public TagBlock OddballEvents;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("king events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine King Event Block", 128, typeof(GameEngineKingEventBlock))]
        public TagBlock KingEvents;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("juggernaut events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Juggernaut Event Block", 128, typeof(GameEngineJuggernautEventBlock))]
        public TagBlock JuggernautEvents;
        [Abide.Guerilla.Tags.FieldAttribute("territories events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Territories Event Block", 128, typeof(GameEngineTerritoriesEventBlock))]
        public TagBlock TerritoriesEvents;
        [Abide.Guerilla.Tags.FieldAttribute("invasion events", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Assault Event Block", 128, typeof(GameEngineAssaultEventBlock))]
        public TagBlock InvasionEvents;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString7;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString8;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString9;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString10;
        [Abide.Guerilla.Tags.FieldAttribute("default item collection 1", typeof(TagReference))]
        public TagReference DefaultItemCollection1;
        [Abide.Guerilla.Tags.FieldAttribute("default item collection 2", typeof(TagReference))]
        public TagReference DefaultItemCollection2;
        [Abide.Guerilla.Tags.FieldAttribute("default frag grenade count", typeof(Int32))]
        public Int32 DefaultFragGrenadeCount;
        [Abide.Guerilla.Tags.FieldAttribute("default plasma grenade count", typeof(Int32))]
        public Int32 DefaultPlasmaGrenadeCount;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(40)]
        public Byte[] EmptyString11;
        [Abide.Guerilla.Tags.FieldAttribute("dynamic zone upper height", typeof(Single))]
        public Single DynamicZoneUpperHeight;
        [Abide.Guerilla.Tags.FieldAttribute("dynamic zone lower height", typeof(Single))]
        public Single DynamicZoneLowerHeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(40)]
        public Byte[] EmptyString12;
        [Abide.Guerilla.Tags.FieldAttribute("enemy inner radius", typeof(Single))]
        public Single EnemyInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("enemy outer radius", typeof(Single))]
        public Single EnemyOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("enemy weight", typeof(Single))]
        public Single EnemyWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString13;
        [Abide.Guerilla.Tags.FieldAttribute("friend inner radius", typeof(Single))]
        public Single FriendInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("friend outer radius", typeof(Single))]
        public Single FriendOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("friend weight", typeof(Single))]
        public Single FriendWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString14;
        [Abide.Guerilla.Tags.FieldAttribute("enemy vehicle inner radius", typeof(Single))]
        public Single EnemyVehicleInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("enemy vehicle outer radius", typeof(Single))]
        public Single EnemyVehicleOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("enemy vehicle weight", typeof(Single))]
        public Single EnemyVehicleWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString15;
        [Abide.Guerilla.Tags.FieldAttribute("friendly vehicle inner radius", typeof(Single))]
        public Single FriendlyVehicleInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("friendly vehicle outer radius", typeof(Single))]
        public Single FriendlyVehicleOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("friendly vehicle weight", typeof(Single))]
        public Single FriendlyVehicleWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString16;
        [Abide.Guerilla.Tags.FieldAttribute("empty vehicle inner radius", typeof(Single))]
        public Single EmptyVehicleInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("empty vehicle outer radius", typeof(Single))]
        public Single EmptyVehicleOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("empty vehicle weight", typeof(Single))]
        public Single EmptyVehicleWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString17;
        [Abide.Guerilla.Tags.FieldAttribute("oddball inclusion inner radius", typeof(Single))]
        public Single OddballInclusionInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("oddball inclusion outer radius", typeof(Single))]
        public Single OddballInclusionOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("oddball inclusion weight", typeof(Single))]
        public Single OddballInclusionWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString18;
        [Abide.Guerilla.Tags.FieldAttribute("oddball exclusion inner radius", typeof(Single))]
        public Single OddballExclusionInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("oddball exclusion outer radius", typeof(Single))]
        public Single OddballExclusionOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("oddball exclusion weight", typeof(Single))]
        public Single OddballExclusionWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString19;
        [Abide.Guerilla.Tags.FieldAttribute("hill inclusion inner radius", typeof(Single))]
        public Single HillInclusionInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("hill inclusion outer radius", typeof(Single))]
        public Single HillInclusionOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("hill inclusion weight", typeof(Single))]
        public Single HillInclusionWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString20;
        [Abide.Guerilla.Tags.FieldAttribute("hill exclusion inner radius", typeof(Single))]
        public Single HillExclusionInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("hill exclusion outer radius", typeof(Single))]
        public Single HillExclusionOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("hill exclusion weight", typeof(Single))]
        public Single HillExclusionWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString21;
        [Abide.Guerilla.Tags.FieldAttribute("last race flag inner radius", typeof(Single))]
        public Single LastRaceFlagInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("last race flag outer radius", typeof(Single))]
        public Single LastRaceFlagOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("last race flag weight", typeof(Single))]
        public Single LastRaceFlagWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString22;
        [Abide.Guerilla.Tags.FieldAttribute("dead ally inner radius", typeof(Single))]
        public Single DeadAllyInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("dead ally outer radius", typeof(Single))]
        public Single DeadAllyOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("dead ally weight", typeof(Single))]
        public Single DeadAllyWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString23;
        [Abide.Guerilla.Tags.FieldAttribute("controlled territory inner radius", typeof(Single))]
        public Single ControlledTerritoryInnerRadius;
        [Abide.Guerilla.Tags.FieldAttribute("controlled territory outer radius", typeof(Single))]
        public Single ControlledTerritoryOuterRadius;
        [Abide.Guerilla.Tags.FieldAttribute("controlled territory weight", typeof(Single))]
        public Single ControlledTerritoryWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString24;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(560)]
        public Byte[] EmptyString25;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(48)]
        public Byte[] EmptyString26;
        [Abide.Guerilla.Tags.FieldAttribute("multiplayer constants", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Multiplayer Constants Block", 1, typeof(MultiplayerConstantsBlock))]
        public TagBlock MultiplayerConstants;
        [Abide.Guerilla.Tags.FieldAttribute("state responses", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Game Engine Status Response Block", 32, typeof(GameEngineStatusResponseBlock))]
        public TagBlock StateResponses;
        [Abide.Guerilla.Tags.FieldAttribute("scoreboard hud definition", typeof(TagReference))]
        public TagReference ScoreboardHudDefinition;
        [Abide.Guerilla.Tags.FieldAttribute("scoreboard emblem shader", typeof(TagReference))]
        public TagReference ScoreboardEmblemShader;
        [Abide.Guerilla.Tags.FieldAttribute("scoreboard emblem bitmap", typeof(TagReference))]
        public TagReference ScoreboardEmblemBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("scoreboard dead emblem shader", typeof(TagReference))]
        public TagReference ScoreboardDeadEmblemShader;
        [Abide.Guerilla.Tags.FieldAttribute("scoreboard dead emblem bitmap", typeof(TagReference))]
        public TagReference ScoreboardDeadEmblemBitmap;
    }
}
#pragma warning restore CS1591
