#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class NewHudDashlightDataStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("low clip cutoff#the cutoff for showing the reload dashlight", typeof(Int16))]
        public Int16 LowClipCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("low ammo cutoff#the cutoff for showing the low ammo dashlight", typeof(Int16))]
        public Int16 LowAmmoCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("age cutoff#the age cutoff for showing the low battery dashlight", typeof(Single))]
        public Single AgeCutoff;
    }
}
#pragma warning restore CS1591
