#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(24, 4)]
    public class NodeRenderLeavesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("collision leaves*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Bsp Leaf Block", 65536, typeof(BspLeafBlock))]
        public TagBlock CollisionLeaves;
        [Abide.Guerilla.Tags.FieldAttribute("surface references*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Bsp Surface Reference Block", 262144, typeof(BspSurfaceReferenceBlock))]
        public TagBlock SurfaceReferences;
    }
}
#pragma warning restore CS1591
