#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(24, 4)]
    public class ObjectChangeColors
    {
        [Abide.Guerilla.Tags.FieldAttribute("initial permutations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Object Change Color Initial Permutation", 32, typeof(ObjectChangeColorInitialPermutation))]
        public TagBlock InitialPermutations;
        [Abide.Guerilla.Tags.FieldAttribute("functions", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Object Change Color Function", 4, typeof(ObjectChangeColorFunction))]
        public TagBlock Functions;
    }
}
#pragma warning restore CS1591
