#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class ObjectAttachmentBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("type^", typeof(TagReference))]
        public TagReference Type;
        [Abide.Guerilla.Tags.FieldAttribute("marker", typeof(StringId))]
        public StringId Marker;
        [Abide.Guerilla.Tags.FieldAttribute("change color", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ChangeColorOptions), false)]
        public Int16 ChangeColor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("primary scale", typeof(StringId))]
        public StringId PrimaryScale;
        [Abide.Guerilla.Tags.FieldAttribute("secondary scale", typeof(StringId))]
        public StringId SecondaryScale;
        public enum ChangeColorOptions
        {
            None = 0,
            Primary = 1,
            Secondary = 2,
            Tertiary = 3,
            Quaternary = 4,
        }
    }
}
#pragma warning restore CS1591
