#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class ParticlesUpdateDataBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("velocity.x*", typeof(Single))]
        public Single Velocityx;
        [Abide.Guerilla.Tags.FieldAttribute("velocity.y*", typeof(Single))]
        public Single Velocityy;
        [Abide.Guerilla.Tags.FieldAttribute("velocity.z*", typeof(Single))]
        public Single Velocityz;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("mass*", typeof(Single))]
        public Single Mass;
        [Abide.Guerilla.Tags.FieldAttribute("creation time stamp*", typeof(Single))]
        public Single CreationTimeStamp;
    }
}
#pragma warning restore CS1591
