#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(248, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("particle", "prt3", "����", typeof(ParticleBlock))]
    public class ParticleBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("particle billboard style", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ParticleBillboardStyleOptions), false)]
        public Int16 ParticleBillboardStyle;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("first sequence index", typeof(Int16))]
        public Int16 FirstSequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("sequence count", typeof(Int16))]
        public Int16 SequenceCount;
        [Abide.Guerilla.Tags.FieldAttribute("shader template", typeof(TagReference))]
        public TagReference ShaderTemplate;
        [Abide.Guerilla.Tags.FieldAttribute("shader parameters", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Parameter", 64, typeof(GlobalShaderParameterBlock))]
        public TagBlock ShaderParameters1;
        [Abide.Guerilla.Tags.FieldAttribute("color", typeof(ParticlePropertyColorStructNewBlock))]
        public ParticlePropertyColorStructNewBlock Color1;
        [Abide.Guerilla.Tags.FieldAttribute("alpha", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock Alpha1;
        [Abide.Guerilla.Tags.FieldAttribute("scale", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock Scale1;
        [Abide.Guerilla.Tags.FieldAttribute("rotation", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock Rotation1;
        [Abide.Guerilla.Tags.FieldAttribute("frame index", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock FrameIndex1;
        [Abide.Guerilla.Tags.FieldAttribute("collision effect#effect, material effect or sound spawned when this particle coll" +
            "ides with something", typeof(TagReference))]
        public TagReference CollisionEffect;
        [Abide.Guerilla.Tags.FieldAttribute("death effect#effect, material effect or sound spawned when this particle dies", typeof(TagReference))]
        public TagReference DeathEffect;
        [Abide.Guerilla.Tags.FieldAttribute("locations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Effect Locations Block", 32, typeof(EffectLocationsBlock))]
        public TagBlock Locations;
        [Abide.Guerilla.Tags.FieldAttribute("attached particle systems", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Particle System Definition Block New", 32, typeof(ParticleSystemDefinitionBlockNew))]
        public TagBlock AttachedParticleSystems1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Postprocess Definition New Block", 1, typeof(ShaderPostprocessDefinitionNewBlock))]
        public TagBlock EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString6;
        public enum FlagsOptions
        {
            Spins = 1,
            RandomUMirror = 2,
            RandomVMirror = 4,
            FrameAnimationOneShot = 8,
            SelectRandomSequence = 16,
            DisableFrameBlending = 32,
            CanAnimateBackwards = 64,
            ReceiveLightmapLighting = 128,
            TintFromDiffuseTexture = 256,
            DiesAtRest = 512,
            DiesOnStructureCollision = 1024,
            DiesInMedia = 2048,
            DiesInAir = 4096,
            BitmapAuthoredVertically = 8192,
            HasSweetener = 16384,
        }
        public enum ParticleBillboardStyleOptions
        {
            ScreenFacing = 0,
            ParallelToDirection = 1,
            PerpendicularToDirection = 2,
            Vertical = 3,
            Horizontal = 4,
        }
    }
}
#pragma warning restore CS1591
