#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(292, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("particle_model", "PRTM", "����", typeof(ParticleModelBlock))]
    public class ParticleModelBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("orientation", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(OrientationOptions), false)]
        public Int32 Orientation;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("shader", typeof(TagReference))]
        public TagReference Shader;
        [Abide.Guerilla.Tags.FieldAttribute("scale x", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock ScaleX1;
        [Abide.Guerilla.Tags.FieldAttribute("scale y", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock ScaleY1;
        [Abide.Guerilla.Tags.FieldAttribute("scale z", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock ScaleZ1;
        [Abide.Guerilla.Tags.FieldAttribute("rotation", typeof(ParticlePropertyScalarStructNewBlock))]
        public ParticlePropertyScalarStructNewBlock Rotation1;
        [Abide.Guerilla.Tags.FieldAttribute("collision effect#effect, material effect or sound spawned when this particle coll" +
            "ides with something", typeof(TagReference))]
        public TagReference CollisionEffect;
        [Abide.Guerilla.Tags.FieldAttribute("death effect#effect, material effect or sound spawned when this particle dies", typeof(TagReference))]
        public TagReference DeathEffect;
        [Abide.Guerilla.Tags.FieldAttribute("locations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Effect Locations Block", 32, typeof(EffectLocationsBlock))]
        public TagBlock Locations;
        [Abide.Guerilla.Tags.FieldAttribute("attached particle systems", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Particle System Definition Block New", 32, typeof(ParticleSystemDefinitionBlockNew))]
        public TagBlock AttachedParticleSystems1;
        [Abide.Guerilla.Tags.FieldAttribute("models*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Particle Models Block", 256, typeof(ParticleModelsBlock))]
        public TagBlock Models;
        [Abide.Guerilla.Tags.FieldAttribute("raw vertices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Particle Model Vertices Block", 32768, typeof(ParticleModelVerticesBlock))]
        public TagBlock RawVertices;
        [Abide.Guerilla.Tags.FieldAttribute("indices*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Particle Model Indices Block", 32768, typeof(ParticleModelIndicesBlock))]
        public TagBlock Indices;
        [Abide.Guerilla.Tags.FieldAttribute("cached data", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cached Data Block", 1, typeof(CachedDataBlock))]
        public TagBlock CachedData;
        [Abide.Guerilla.Tags.FieldAttribute("geometry section info", typeof(GlobalGeometryBlockInfoStructBlock))]
        public GlobalGeometryBlockInfoStructBlock GeometrySectionInfo;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString3;
        public enum FlagsOptions
        {
            Spins = 1,
            RandomUMirror = 2,
            RandomVMirror = 4,
            FrameAnimationOneShot = 8,
            SelectRandomSequence = 16,
            DisableFrameBlending = 32,
            CanAnimateBackwards = 64,
            ReceiveLightmapLighting = 128,
            TintFromDiffuseTexture = 256,
            DiesAtRest = 512,
            DiesOnStructureCollision = 1024,
            DiesInMedia = 2048,
            DiesInAir = 4096,
            BitmapAuthoredVertically = 8192,
            HasSweetener = 16384,
        }
        public enum OrientationOptions
        {
            ScreenFacing = 0,
            ParallelToDirection = 1,
            PerpendicularToDirection = 2,
            Vertical = 3,
            Horizontal = 4,
        }
    }
}
#pragma warning restore CS1591
