#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    public class PhysicsModelNodeConstraintEdgeBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("node a*", typeof(Int16))]
        public Int16 NodeA;
        [Abide.Guerilla.Tags.FieldAttribute("node b*", typeof(Int16))]
        public Int16 NodeB;
        [Abide.Guerilla.Tags.FieldAttribute("constraints*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Physics Model Constraint Edge Constraint Block", 64, typeof(PhysicsModelConstraintEdgeConstraintBlock))]
        public TagBlock Constraints;
        [Abide.Guerilla.Tags.FieldAttribute("node a material#if you don\'t fill this out we will pluck the material from the fi" +
            "rst primitive, of the first rigid body attached to node a", typeof(StringId))]
        public StringId NodeAMaterial;
        [Abide.Guerilla.Tags.FieldAttribute("node b material#if you don\'t fill this out we will pluck the material from the fi" +
            "rst primitive, of the first rigid body attached to node b, if node b is none we " +
            "use whatever material a has", typeof(StringId))]
        public StringId NodeBMaterial;
    }
}
#pragma warning restore CS1591
