#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class PixelShaderCombinerBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(16)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("constant color0", typeof(ColorArgb))]
        public ColorArgb ConstantColor0;
        [Abide.Guerilla.Tags.FieldAttribute("constant color1", typeof(ColorArgb))]
        public ColorArgb ConstantColor1;
        [Abide.Guerilla.Tags.FieldAttribute("color A register ptr index", typeof(Byte))]
        public Byte ColorARegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("color B register ptr index", typeof(Byte))]
        public Byte ColorBRegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("color C register ptr index", typeof(Byte))]
        public Byte ColorCRegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("color D register ptr index", typeof(Byte))]
        public Byte ColorDRegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("alpha A register ptr index", typeof(Byte))]
        public Byte AlphaARegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("alpha B register ptr index", typeof(Byte))]
        public Byte AlphaBRegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("alpha C register ptr index", typeof(Byte))]
        public Byte AlphaCRegisterPtrIndex;
        [Abide.Guerilla.Tags.FieldAttribute("alpha D register ptr index", typeof(Byte))]
        public Byte AlphaDRegisterPtrIndex;
    }
}
#pragma warning restore CS1591
