#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(40, 4)]
    public class PlatformSoundEffectBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("function inputs", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Platform Sound Effect Function Block", 16, typeof(PlatformSoundEffectFunctionBlock))]
        public TagBlock FunctionInputs;
        [Abide.Guerilla.Tags.FieldAttribute("constant inputs", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Platform Sound Effect Constant Block", 16, typeof(PlatformSoundEffectConstantBlock))]
        public TagBlock ConstantInputs;
        [Abide.Guerilla.Tags.FieldAttribute("template override descriptors", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Platform Sound Effect Override Descriptor Block", 16, typeof(PlatformSoundEffectOverrideDescriptorBlock))]
        public TagBlock TemplateOverrideDescriptors;
        [Abide.Guerilla.Tags.FieldAttribute("input overrides", typeof(Int32))]
        public Int32 InputOverrides;
    }
}
#pragma warning restore CS1591
