#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class PlatformSoundEffectTemplateComponentBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("value type", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ValueTypeOptions), false)]
        public Int32 ValueType;
        [Abide.Guerilla.Tags.FieldAttribute("default value", typeof(Single))]
        public Single DefaultValue;
        [Abide.Guerilla.Tags.FieldAttribute("minimum value", typeof(Single))]
        public Single MinimumValue;
        [Abide.Guerilla.Tags.FieldAttribute("maximum value", typeof(Single))]
        public Single MaximumValue;
        public enum ValueTypeOptions
        {
            Zero = 0,
            Time = 1,
            Scale = 2,
            Rolloff = 3,
        }
    }
}
#pragma warning restore CS1591
