#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(72, 4)]
    public class PlatformSoundFilterBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("filter type", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FilterTypeOptions), false)]
        public Int32 FilterType;
        [Abide.Guerilla.Tags.FieldAttribute("filter width:[0,7]", typeof(Int32))]
        public Int32 FilterWidth;
        [Abide.Guerilla.Tags.FieldAttribute("left filter frequency", typeof(SoundPlaybackParameterDefinitionBlock))]
        public SoundPlaybackParameterDefinitionBlock LeftFilterFrequency1;
        [Abide.Guerilla.Tags.FieldAttribute("left filter gain", typeof(SoundPlaybackParameterDefinitionBlock))]
        public SoundPlaybackParameterDefinitionBlock LeftFilterGain1;
        [Abide.Guerilla.Tags.FieldAttribute("right filter frequency", typeof(SoundPlaybackParameterDefinitionBlock))]
        public SoundPlaybackParameterDefinitionBlock RightFilterFrequency1;
        [Abide.Guerilla.Tags.FieldAttribute("right filter gain", typeof(SoundPlaybackParameterDefinitionBlock))]
        public SoundPlaybackParameterDefinitionBlock RightFilterGain1;
        public enum FilterTypeOptions
        {
            ParametricEq = 0,
            Dls2 = 1,
            BothOnlyValidForMono = 2,
        }
    }
}
#pragma warning restore CS1591
