#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class PlatformSoundOverrideMixbinsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("mixbin", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(MixbinOptions), false)]
        public Int32 Mixbin;
        [Abide.Guerilla.Tags.FieldAttribute("gain:dB", typeof(Single))]
        public Single Gain;
        public enum MixbinOptions
        {
            FrontLeft = 0,
            FrontRight = 1,
            BackLeft = 2,
            BackRight = 3,
            Center = 4,
            LowFrequency = 5,
            Reverb = 6,
            _3dFrontLeft = 7,
            _3dFrontRight = 8,
            _3dBackLeft = 9,
            _3dBackRight = 10,
            DefaultLeftSpeakers = 11,
            DefaultRightSpeakers = 12,
        }
    }
}
#pragma warning restore CS1591
