#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class PlayerBlockReferenceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("skin", typeof(TagReference))]
        public TagReference Skin;
        [Abide.Guerilla.Tags.FieldAttribute("bottom-left", typeof(Vector2))]
        public Vector2 Bottomleft;
        [Abide.Guerilla.Tags.FieldAttribute("table order", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(TableOrderOptions), false)]
        public Byte TableOrder;
        [Abide.Guerilla.Tags.FieldAttribute("maximum player count", typeof(Byte))]
        public Byte MaximumPlayerCount;
        [Abide.Guerilla.Tags.FieldAttribute("row count", typeof(Byte))]
        public Byte RowCount;
        [Abide.Guerilla.Tags.FieldAttribute("column count", typeof(Byte))]
        public Byte ColumnCount;
        [Abide.Guerilla.Tags.FieldAttribute("row height", typeof(Int16))]
        public Int16 RowHeight;
        [Abide.Guerilla.Tags.FieldAttribute("column width", typeof(Int16))]
        public Int16 ColumnWidth;
        public enum TableOrderOptions
        {
            RowMajor = 0,
            ColumnMajor = 1,
        }
    }
}
#pragma warning restore CS1591
