#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    public class PlayerTrainingEntryDataBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("display string#comes out of the HUD text globals", typeof(StringId))]
        public StringId DisplayString;
        [Abide.Guerilla.Tags.FieldAttribute("display string2#comes out of the HUD text globals, used for grouped prompt", typeof(StringId))]
        public StringId DisplayString2;
        [Abide.Guerilla.Tags.FieldAttribute("display string3#comes out of the HUD text globals, used for ungrouped prompt", typeof(StringId))]
        public StringId DisplayString3;
        [Abide.Guerilla.Tags.FieldAttribute("max display time#how long the message can be on screen before being hidden", typeof(Int16))]
        public Int16 MaxDisplayTime;
        [Abide.Guerilla.Tags.FieldAttribute("display count#how many times a training message will get displayed (0-3 only!)", typeof(Int16))]
        public Int16 DisplayCount;
        [Abide.Guerilla.Tags.FieldAttribute("dissapear delay#how long a displayed but untriggered message stays up", typeof(Int16))]
        public Int16 DissapearDelay;
        [Abide.Guerilla.Tags.FieldAttribute("redisplay delay#how long after display this message will stay hidden", typeof(Int16))]
        public Int16 RedisplayDelay;
        [Abide.Guerilla.Tags.FieldAttribute("display delay (s)#how long the event can be triggered before it\'s displayed", typeof(Single))]
        public Single DisplayDelayS;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        public enum FlagsOptions
        {
            NotInMultiplayer = 1,
        }
    }
}
#pragma warning restore CS1591
