#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(64, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("point_physics", "pphy", "����", typeof(PointPhysicsBlock))]
    public class PointPhysicsBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(28)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("density:g/mL", typeof(Single))]
        public Single Density;
        [Abide.Guerilla.Tags.FieldAttribute("air friction", typeof(Single))]
        public Single AirFriction;
        [Abide.Guerilla.Tags.FieldAttribute("water friction", typeof(Single))]
        public Single WaterFriction;
        [Abide.Guerilla.Tags.FieldAttribute("surface friction#when hitting the ground or interior, percentage of velocity lost" +
            " in one collision", typeof(Single))]
        public Single SurfaceFriction;
        [Abide.Guerilla.Tags.FieldAttribute("elasticity#0.0 is inelastic collisions (no bounce) 1.0 is perfectly elastic (refl" +
            "ected velocity equals incoming velocity)", typeof(Single))]
        public Single Elasticity;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString1;
        public enum FlagsOptions
        {
            Unused = 1,
            CollidesWithStructures = 2,
            CollidesWithWaterSurface = 4,
            UsesSimpleWind = 8,
            UsesDampedWind = 16,
            NoGravity = 32,
        }
    }
}
#pragma warning restore CS1591
