#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(40, 4)]
    public class PrimaryLightStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Min lightmap color", typeof(ColorRgbF))]
        public ColorRgbF MinLightmapColor;
        [Abide.Guerilla.Tags.FieldAttribute("Max lightmap color", typeof(ColorRgbF))]
        public ColorRgbF MaxLightmapColor;
        [Abide.Guerilla.Tags.FieldAttribute("exclusion angle from up#degrees from up the direct light cannot be", typeof(Single))]
        public Single ExclusionAngleFromUp;
        [Abide.Guerilla.Tags.FieldAttribute("function", typeof(MappingFunctionBlock))]
        public MappingFunctionBlock Function1;
    }
}
#pragma warning restore CS1591
