#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    public class RenderModelRegionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name^*", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("node map offset (OLD)*", typeof(Int16))]
        public Int16 NodeMapOffsetOld;
        [Abide.Guerilla.Tags.FieldAttribute("node map size (OLD)*", typeof(Int16))]
        public Int16 NodeMapSizeOld;
        [Abide.Guerilla.Tags.FieldAttribute("permutations*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Permutation", 32, typeof(RenderModelPermutationBlock))]
        public TagBlock Permutations;
    }
}
#pragma warning restore CS1591
