#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(5, 4)]
    public class RenderStateBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("state index", typeof(Byte))]
        public Byte StateIndex;
        [Abide.Guerilla.Tags.FieldAttribute("state value", typeof(Int32))]
        public Int32 StateValue;
    }
}
#pragma warning restore CS1591
