#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(268, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("scenario_structure_lightmap", "ltmp", "����", typeof(ScenarioStructureLightmapBlock))]
    public class ScenarioStructureLightmapBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("search distance lower bound", typeof(Single))]
        public Single SearchDistanceLowerBound;
        [Abide.Guerilla.Tags.FieldAttribute("search distance upper bound", typeof(Single))]
        public Single SearchDistanceUpperBound;
        [Abide.Guerilla.Tags.FieldAttribute("luminels per world unit", typeof(Single))]
        public Single LuminelsPerWorldUnit;
        [Abide.Guerilla.Tags.FieldAttribute("output white reference", typeof(Single))]
        public Single OutputWhiteReference;
        [Abide.Guerilla.Tags.FieldAttribute("output black reference", typeof(Single))]
        public Single OutputBlackReference;
        [Abide.Guerilla.Tags.FieldAttribute("output schlick parameter", typeof(Single))]
        public Single OutputSchlickParameter;
        [Abide.Guerilla.Tags.FieldAttribute("diffuse map scale", typeof(Single))]
        public Single DiffuseMapScale;
        [Abide.Guerilla.Tags.FieldAttribute("sun scale", typeof(Single))]
        public Single SunScale;
        [Abide.Guerilla.Tags.FieldAttribute("sky scale", typeof(Single))]
        public Single SkyScale;
        [Abide.Guerilla.Tags.FieldAttribute("indirect scale", typeof(Single))]
        public Single IndirectScale;
        [Abide.Guerilla.Tags.FieldAttribute("prt scale", typeof(Single))]
        public Single PrtScale;
        [Abide.Guerilla.Tags.FieldAttribute("surface light scale", typeof(Single))]
        public Single SurfaceLightScale;
        [Abide.Guerilla.Tags.FieldAttribute("scenario light scale", typeof(Single))]
        public Single ScenarioLightScale;
        [Abide.Guerilla.Tags.FieldAttribute("lightprobe interpolation overide", typeof(Single))]
        public Single LightprobeInterpolationOveride;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(72)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("lightmap groups", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Structure Lightmap Group Block", 256, typeof(StructureLightmapGroupBlock))]
        public TagBlock LightmapGroups;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("errors*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Error Report Category", 64, typeof(GlobalErrorReportCategoriesBlock))]
        public TagBlock Errors;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(104)]
        public Byte[] EmptyString2;
    }
}
#pragma warning restore CS1591
