#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(80, 4)]
    public class ScenarioClusterDataBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("BSP*", typeof(TagReference))]
        public TagReference Bsp;
        [Abide.Guerilla.Tags.FieldAttribute("Background Sounds*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Cluster Background Sounds Block", 512, typeof(ScenarioClusterBackgroundSoundsBlock))]
        public TagBlock BackgroundSounds;
        [Abide.Guerilla.Tags.FieldAttribute("Sound Environments*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Cluster Sound Environments Block", 512, typeof(ScenarioClusterSoundEnvironmentsBlock))]
        public TagBlock SoundEnvironments;
        [Abide.Guerilla.Tags.FieldAttribute("BSP Checksum*", typeof(Int32))]
        public Int32 BspChecksum;
        [Abide.Guerilla.Tags.FieldAttribute("Cluster Centroids*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Cluster Points Block", 512, typeof(ScenarioClusterPointsBlock))]
        public TagBlock ClusterCentroids;
        [Abide.Guerilla.Tags.FieldAttribute("Weather Properties*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Cluster Weather Properties Block", 512, typeof(ScenarioClusterWeatherPropertiesBlock))]
        public TagBlock WeatherProperties;
        [Abide.Guerilla.Tags.FieldAttribute("Atmospheric Fog Properties*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Cluster Atmospheric Fog Properties Block", 512, typeof(ScenarioClusterAtmosphericFogPropertiesBlock))]
        public TagBlock AtmosphericFogProperties;
    }
}
#pragma warning restore CS1591
