#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(228, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("scenario_ai_resource", "ai**", "����", typeof(ScenarioAiResourceBlock))]
    public class ScenarioAiResourceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Style Palette", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Style Palette Block", 50, typeof(StylePaletteBlock))]
        public TagBlock StylePalette;
        [Abide.Guerilla.Tags.FieldAttribute("Squad Groups", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Squad Groups Block", 100, typeof(SquadGroupsBlock))]
        public TagBlock SquadGroups;
        [Abide.Guerilla.Tags.FieldAttribute("Squads", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Squads Block", 335, typeof(SquadsBlock))]
        public TagBlock Squads;
        [Abide.Guerilla.Tags.FieldAttribute("Zones", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Zone Block", 128, typeof(ZoneBlock))]
        public TagBlock Zones;
        [Abide.Guerilla.Tags.FieldAttribute("Character Palette", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Character Palette Block", 64, typeof(CharacterPaletteBlock))]
        public TagBlock CharacterPalette;
        [Abide.Guerilla.Tags.FieldAttribute("AI Animation References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Animation Reference Block", 128, typeof(AiAnimationReferenceBlock))]
        public TagBlock AiAnimationReferences;
        [Abide.Guerilla.Tags.FieldAttribute("AI Script References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Script Reference Block", 128, typeof(AiScriptReferenceBlock))]
        public TagBlock AiScriptReferences;
        [Abide.Guerilla.Tags.FieldAttribute("AI Recording References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Recording Reference Block", 128, typeof(AiRecordingReferenceBlock))]
        public TagBlock AiRecordingReferences;
        [Abide.Guerilla.Tags.FieldAttribute("AI Conversations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Conversation Block", 128, typeof(AiConversationBlock))]
        public TagBlock AiConversations;
        [Abide.Guerilla.Tags.FieldAttribute("Scripting Data", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Cs Script Data Block", 1, typeof(CsScriptDataBlock))]
        public TagBlock ScriptingData;
        [Abide.Guerilla.Tags.FieldAttribute("Orders", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Orders Block", 300, typeof(OrdersBlock))]
        public TagBlock Orders;
        [Abide.Guerilla.Tags.FieldAttribute("Triggers", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Triggers Block", 256, typeof(TriggersBlock))]
        public TagBlock Triggers;
        [Abide.Guerilla.Tags.FieldAttribute("BSP Preferences", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Structure Bsp Reference Block", 16, typeof(ScenarioStructureBspReferenceBlock))]
        public TagBlock BspPreferences;
        [Abide.Guerilla.Tags.FieldAttribute("Weapon References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Weapon Palette Block", 256, typeof(ScenarioWeaponPaletteBlock))]
        public TagBlock WeaponReferences;
        [Abide.Guerilla.Tags.FieldAttribute("Vehicle References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Vehicle Palette Block", 256, typeof(ScenarioVehiclePaletteBlock))]
        public TagBlock VehicleReferences;
        [Abide.Guerilla.Tags.FieldAttribute("Vehicle Datum References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Vehicle Block", 256, typeof(ScenarioVehicleBlock))]
        public TagBlock VehicleDatumReferences;
        [Abide.Guerilla.Tags.FieldAttribute("Mission Dialogue Scenes", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ai Scene Block", 100, typeof(AiSceneBlock))]
        public TagBlock MissionDialogueScenes;
        [Abide.Guerilla.Tags.FieldAttribute("Flocks", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Flock Definition Block", 20, typeof(FlockDefinitionBlock))]
        public TagBlock Flocks;
        [Abide.Guerilla.Tags.FieldAttribute("Trigger Volume References", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Scenario Trigger Volume Block", 256, typeof(ScenarioTriggerVolumeBlock))]
        public TagBlock TriggerVolumeReferences;
    }
}
#pragma warning restore CS1591
