#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(48, 4)]
    public class ScenarioObjectDatumStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Placement Flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(PlacementFlagsOptions), true)]
        public Int32 PlacementFlags;
        [Abide.Guerilla.Tags.FieldAttribute("Position", typeof(Vector3))]
        public Vector3 Position;
        [Abide.Guerilla.Tags.FieldAttribute("Rotation", typeof(Vector3))]
        public Vector3 Rotation;
        [Abide.Guerilla.Tags.FieldAttribute("Scale", typeof(Single))]
        public Single Scale;
        [Abide.Guerilla.Tags.FieldAttribute(")Transform Flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(TransformFlagsOptions), true)]
        public Int16 TransformFlags;
        [Abide.Guerilla.Tags.FieldAttribute("Manual BSP Flags*", typeof(Int16))]
        public Int16 ManualBspFlags;
        [Abide.Guerilla.Tags.FieldAttribute("Object ID", typeof(ScenarioObjectIdStructBlock))]
        public ScenarioObjectIdStructBlock ObjectId;
        [Abide.Guerilla.Tags.FieldAttribute("BSP Policy", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(BspPolicyOptions), false)]
        public Byte BspPolicy;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(1)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Editor Folder", typeof(Int16))]
        public Int16 EditorFolder;
        public enum PlacementFlagsOptions
        {
            NotAutomatically = 1,
            Unused = 2,
            Unused1 = 4,
            Unused2 = 8,
            LockTypeToEnvObject = 16,
            LockTransformToEnvObject = 32,
            NeverPlaced = 64,
            LockNameToEnvObject = 128,
            CreateAtRest = 256,
        }
        public enum TransformFlagsOptions
        {
            Mirrored = 1,
        }
        public enum BspPolicyOptions
        {
            Default = 0,
            AlwaysPlaced = 1,
            ManualBspPlacement = 2,
        }
    }
}
#pragma warning restore CS1591
