#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(24, 4)]
    public class ScenarioObjectPermutationStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Variant Name", typeof(StringId))]
        public StringId VariantName;
        [Abide.Guerilla.Tags.FieldAttribute("Active Change Colors", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ActiveChangeColorsOptions), true)]
        public Int32 ActiveChangeColors;
        [Abide.Guerilla.Tags.FieldAttribute("Primary Color", typeof(ColorRgb))]
        public ColorRgb PrimaryColor;
        [Abide.Guerilla.Tags.FieldAttribute("Secondary Color", typeof(ColorRgb))]
        public ColorRgb SecondaryColor;
        [Abide.Guerilla.Tags.FieldAttribute("Tertiary Color", typeof(ColorRgb))]
        public ColorRgb TertiaryColor;
        [Abide.Guerilla.Tags.FieldAttribute("Quaternary Color", typeof(ColorRgb))]
        public ColorRgb QuaternaryColor;
        public enum ActiveChangeColorsOptions
        {
            Primary = 1,
            Secondary = 2,
            Tertiary = 4,
            Quaternary = 8,
        }
    }
}
#pragma warning restore CS1591
