#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(256, 4)]
    public class ScenarioAtmosphericFogPalette
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name^", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("Color", typeof(ColorRgbF))]
        public ColorRgbF Color;
        [Abide.Guerilla.Tags.FieldAttribute("Spread Distance:World Units#How far fog spreads into adjacent clusters: 0 default" +
            "s to 1.", typeof(Single))]
        public Single SpreadDistance;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Maximum Density:[0,1]#Fog density clamps to this value.", typeof(Single))]
        public Single MaximumDensity;
        [Abide.Guerilla.Tags.FieldAttribute("Start Distance:World Units#Before this distance, there is no fog.", typeof(Single))]
        public Single StartDistance;
        [Abide.Guerilla.Tags.FieldAttribute("Opaque Distance:World Units#Fog becomes opaque (maximum density) at this distance" +
            " from viewer.", typeof(Single))]
        public Single OpaqueDistance;
        [Abide.Guerilla.Tags.FieldAttribute("Color", typeof(ColorRgbF))]
        public ColorRgbF Color1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Maximum Density:[0,1]#Fog density clamps to this value.", typeof(Single))]
        public Single MaximumDensity1;
        [Abide.Guerilla.Tags.FieldAttribute("Start Distance:World Units#Before this distance, there is no fog.", typeof(Single))]
        public Single StartDistance1;
        [Abide.Guerilla.Tags.FieldAttribute("Opaque Distance:World Units#Fog becomes opaque (maximum density) at this distance" +
            " from viewer.", typeof(Single))]
        public Single OpaqueDistance1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("Planar Color", typeof(ColorRgbF))]
        public ColorRgbF PlanarColor;
        [Abide.Guerilla.Tags.FieldAttribute("Planar Max Density:[0,1]", typeof(Single))]
        public Single PlanarMaxDensity;
        [Abide.Guerilla.Tags.FieldAttribute("Planar Override Amount:[0,1]", typeof(Single))]
        public Single PlanarOverrideAmount;
        [Abide.Guerilla.Tags.FieldAttribute("Planar Min Distance Bias:World Units#Don\'t ask.", typeof(Single))]
        public Single PlanarMinDistanceBias;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(44)]
        public Byte[] EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("Patchy Color", typeof(ColorRgbF))]
        public ColorRgbF PatchyColor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(12)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("Patchy Fog", typeof(TagReference))]
        public TagReference PatchyFog1;
        [Abide.Guerilla.Tags.FieldAttribute("Mixers", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Mixers", 2, typeof(ScenarioAtmosphericFogMixerBlock))]
        public TagBlock Mixers;
        [Abide.Guerilla.Tags.FieldAttribute("Amount:[0,1]", typeof(Single))]
        public Single Amount;
        [Abide.Guerilla.Tags.FieldAttribute("Threshold:[0,1]", typeof(Single))]
        public Single Threshold;
        [Abide.Guerilla.Tags.FieldAttribute("Brightness:[0,1]", typeof(Single))]
        public Single Brightness;
        [Abide.Guerilla.Tags.FieldAttribute("Gamma Power", typeof(Single))]
        public Single GammaPower;
        [Abide.Guerilla.Tags.FieldAttribute("Camera Immersion Flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(CameraImmersionFlagsOptions), true)]
        public Int16 CameraImmersionFlags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString6;
        public enum CameraImmersionFlagsOptions
        {
            DisableAtmosphericFog = 1,
            DisableSecondaryFog = 2,
            DisablePlanarFog = 4,
            InvertPlanarFogPriorities = 8,
            DisableWater = 16,
        }
    }
}
#pragma warning restore CS1591
