#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(156, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("screen_effect", "egor", "����", typeof(ScreenEffectBlock))]
    public class ScreenEffectBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(64)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("shader", typeof(TagReference))]
        public TagReference Shader;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(64)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("pass references", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Pass Reference", 8, typeof(RasterizerScreenEffectPassReferenceBlock))]
        public TagBlock PassReferences;
    }
}
#pragma warning restore CS1591
