#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    public class SectorBsp2dNodesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("plane*", typeof(Vector3))]
        public Vector3 Plane;
        [Abide.Guerilla.Tags.FieldAttribute("left child*", typeof(Int32))]
        public Int32 LeftChild;
        [Abide.Guerilla.Tags.FieldAttribute("right child*", typeof(Int32))]
        public Int32 RightChild;
    }
}
#pragma warning restore CS1591
