#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("shader_light_response", "slit", "����", typeof(ShaderLightResponseBlock))]
    public class ShaderLightResponseBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("categories", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Category", 16, typeof(ShaderTemplateCategoryBlock))]
        public TagBlock Categories;
        [Abide.Guerilla.Tags.FieldAttribute("shader LODs", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Template Level Of Detail Block", 8, typeof(ShaderTemplateLevelOfDetailBlock))]
        public TagBlock ShaderLods;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
    }
}
#pragma warning restore CS1591
