#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(12, 4)]
    public class ShaderPostprocessBitmapNewBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("bitmap group", typeof(Int32))]
        public Int32 BitmapGroup;
        [Abide.Guerilla.Tags.FieldAttribute("bitmap index", typeof(Int32))]
        public Int32 BitmapIndex;
        [Abide.Guerilla.Tags.FieldAttribute("log bitmap dimension", typeof(Single))]
        public Single LogBitmapDimension;
    }
}
#pragma warning restore CS1591
