#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(132, 4)]
    public class ShaderPassPostprocessDefinitionNewBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("implementations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Implementation New Block", 1024, typeof(ShaderPassPostprocessImplementationNewBlock))]
        public TagBlock Implementations;
        [Abide.Guerilla.Tags.FieldAttribute("textures", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Texture New Block", 1024, typeof(ShaderPassPostprocessTextureNewBlock))]
        public TagBlock Textures;
        [Abide.Guerilla.Tags.FieldAttribute("render states", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Render State Block", 1024, typeof(RenderStateBlock))]
        public TagBlock RenderStates;
        [Abide.Guerilla.Tags.FieldAttribute("texture states", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Texture State Block", 1024, typeof(ShaderPassPostprocessTextureStateBlock))]
        public TagBlock TextureStates;
        [Abide.Guerilla.Tags.FieldAttribute("ps fragments", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Pixel Shader Fragment Block", 1024, typeof(PixelShaderFragmentBlock))]
        public TagBlock PsFragments;
        [Abide.Guerilla.Tags.FieldAttribute("ps permutations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Pixel Shader Permutation New Block", 1024, typeof(PixelShaderPermutationNewBlock))]
        public TagBlock PsPermutations;
        [Abide.Guerilla.Tags.FieldAttribute("ps combiners", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Pixel Shader Combiner Block", 1024, typeof(PixelShaderCombinerBlock))]
        public TagBlock PsCombiners;
        [Abide.Guerilla.Tags.FieldAttribute("externs", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Extern New Block", 1024, typeof(ShaderPassPostprocessExternNewBlock))]
        public TagBlock Externs;
        [Abide.Guerilla.Tags.FieldAttribute("constants", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Constant New Block", 1024, typeof(ShaderPassPostprocessConstantNewBlock))]
        public TagBlock Constants;
        [Abide.Guerilla.Tags.FieldAttribute("constant info", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Constant Info New Block", 1024, typeof(ShaderPassPostprocessConstantInfoNewBlock))]
        public TagBlock ConstantInfo;
        [Abide.Guerilla.Tags.FieldAttribute("old implementations", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Shader Pass Postprocess Implementation Block", 1024, typeof(ShaderPassPostprocessImplementationBlock))]
        public TagBlock OldImplementations;
    }
}
#pragma warning restore CS1591
