#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class ShaderStateAlphaTestStateBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("alpha compare function", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(AlphaCompareFunctionOptions), false)]
        public Int16 AlphaCompareFunction;
        [Abide.Guerilla.Tags.FieldAttribute("alpha-test ref:[0,255]", typeof(Int16))]
        public Int16 AlphatestRef;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        public enum FlagsOptions
        {
            AlphatestEnabled = 1,
            SamplealphaToCoverage = 2,
            SamplealphaToOne = 4,
        }
        public enum AlphaCompareFunctionOptions
        {
            Never = 0,
            Less = 1,
            Equal = 2,
            LessOrEqual = 3,
            Greater = 4,
            NotEqual = 5,
            GreaterOrEqual = 6,
            Always = 7,
        }
    }
}
#pragma warning restore CS1591
