#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(7, 4)]
    public class ShaderPassPostprocessConstantNewBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("parameter name", typeof(StringId))]
        public StringId ParameterName;
        [Abide.Guerilla.Tags.FieldAttribute("component mask", typeof(Byte))]
        public Byte ComponentMask;
        [Abide.Guerilla.Tags.FieldAttribute("scale by texture stage", typeof(Byte))]
        public Byte ScaleByTextureStage;
        [Abide.Guerilla.Tags.FieldAttribute("function index", typeof(Byte))]
        public Byte FunctionIndex;
    }
}
#pragma warning restore CS1591
