#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(44, 4)]
    public class ShaderPostprocessImplementationBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("GPU Constant State", typeof(ShaderGpuStateReferenceStructBlock))]
        public ShaderGpuStateReferenceStructBlock GpuConstantState;
        [Abide.Guerilla.Tags.FieldAttribute("GPU Volatile State", typeof(ShaderGpuStateReferenceStructBlock))]
        public ShaderGpuStateReferenceStructBlock GpuVolatileState;
        [Abide.Guerilla.Tags.FieldAttribute("bitmap parameters", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock BitmapParameters;
        [Abide.Guerilla.Tags.FieldAttribute("bitmap transforms", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock BitmapTransforms;
        [Abide.Guerilla.Tags.FieldAttribute("value parameters", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock ValueParameters;
        [Abide.Guerilla.Tags.FieldAttribute("color parameters", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock ColorParameters;
        [Abide.Guerilla.Tags.FieldAttribute("bitmap transform overlays", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock BitmapTransformOverlays;
        [Abide.Guerilla.Tags.FieldAttribute("value overlays", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock ValueOverlays;
        [Abide.Guerilla.Tags.FieldAttribute("color overlays", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock ColorOverlays;
        [Abide.Guerilla.Tags.FieldAttribute("vertex shader constants", typeof(TagBlockIndexStructBlock))]
        public TagBlockIndexStructBlock VertexShaderConstants;
    }
}
#pragma warning restore CS1591
