#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class ShaderTemplateLevelOfDetailBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Projected Diameter:pixels", typeof(Single))]
        public Single ProjectedDiameter;
        [Abide.Guerilla.Tags.FieldAttribute("Pass", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Pass", 16, typeof(ShaderTemplatePassReferenceBlock))]
        public TagBlock Pass;
    }
}
#pragma warning restore CS1591
