#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(72, 4)]
    public class ShaderTemplateParameterBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name^", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("Explanation", typeof(Byte[]))]
        public Byte[] Explanation;
        [Abide.Guerilla.Tags.FieldAttribute("Type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(TypeOptions), false)]
        public Int16 Type;
        [Abide.Guerilla.Tags.FieldAttribute("Flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("Default Bitmap", typeof(TagReference))]
        public TagReference DefaultBitmap;
        [Abide.Guerilla.Tags.FieldAttribute("Default Const Value", typeof(Single))]
        public Single DefaultConstValue;
        [Abide.Guerilla.Tags.FieldAttribute("Default Const Color", typeof(ColorRgbF))]
        public ColorRgbF DefaultConstColor;
        [Abide.Guerilla.Tags.FieldAttribute("Bitmap Type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(BitmapTypeOptions), false)]
        public Int16 BitmapType;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("Bitmap Animation Flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(BitmapAnimationFlagsOptions), true)]
        public Int16 BitmapAnimationFlags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("Bitmap Scale", typeof(Single))]
        public Single BitmapScale;
        public enum TypeOptions
        {
            Bitmap = 0,
            Value = 1,
            Color = 2,
            Switch = 3,
        }
        public enum FlagsOptions
        {
            Animated = 1,
            HideBitmapReference = 2,
        }
        public enum BitmapTypeOptions
        {
            _2d = 0,
            _3d = 1,
            CubeMap = 2,
        }
        public enum BitmapAnimationFlagsOptions
        {
            ScaleUniform = 1,
            Scale = 2,
            Translation = 4,
            Rotation = 8,
            Index = 16,
        }
    }
}
#pragma warning restore CS1591
