#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class ShaderStateDepthStateBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("mode", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ModeOptions), false)]
        public Int16 Mode;
        [Abide.Guerilla.Tags.FieldAttribute("depth compare function", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(DepthCompareFunctionOptions), false)]
        public Int16 DepthCompareFunction;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("depth bias slope scale", typeof(Single))]
        public Single DepthBiasSlopeScale;
        [Abide.Guerilla.Tags.FieldAttribute("depth bias", typeof(Single))]
        public Single DepthBias;
        public enum ModeOptions
        {
            UseZ = 0,
            UseW = 1,
        }
        public enum DepthCompareFunctionOptions
        {
            Never = 0,
            Less = 1,
            Equal = 2,
            LessOrEqual = 3,
            Greater = 4,
            NotEqual = 5,
            GreaterOrEqual = 6,
            Always = 7,
        }
        public enum FlagsOptions
        {
            DepthWrite = 1,
            OffsetPoints = 2,
            OffsetLines = 4,
            OffsetTriangles = 8,
            ClipControlDontCullPrimitive = 16,
            ClipControlClamp = 32,
            ClipControlIgnoreWSign = 64,
        }
    }
}
#pragma warning restore CS1591
