#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    public class SingleAnimationReferenceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("animation period:milliseconds", typeof(Int32))]
        public Int32 AnimationPeriod;
        [Abide.Guerilla.Tags.FieldAttribute("keyframes", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Screen Animation Keyframe Reference Block", 64, typeof(ScreenAnimationKeyframeReferenceBlock))]
        public TagBlock Keyframes;
        public enum FlagsOptions
        {
            Unused = 1,
        }
    }
}
#pragma warning restore CS1591
