#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class SkyFogBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Color", typeof(ColorRgbF))]
        public ColorRgbF Color;
        [Abide.Guerilla.Tags.FieldAttribute("Density:[0,1]#Fog density is clamped to this value.", typeof(Single))]
        public Single Density;
    }
}
#pragma warning restore CS1591
