#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(72, 4)]
    public class SkyLightBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Direction Vector", typeof(Vector3))]
        public Vector3 DirectionVector;
        [Abide.Guerilla.Tags.FieldAttribute("Direction", typeof(Vector2))]
        public Vector2 Direction;
        [Abide.Guerilla.Tags.FieldAttribute("Lens Flare", typeof(TagReference))]
        public TagReference LensFlare;
        [Abide.Guerilla.Tags.FieldAttribute("Fog", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Sky Light Fog Block", 1, typeof(SkyLightFogBlock))]
        public TagBlock Fog;
        [Abide.Guerilla.Tags.FieldAttribute("Fog Opposite", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Sky Light Fog Block", 1, typeof(SkyLightFogBlock))]
        public TagBlock FogOpposite;
        [Abide.Guerilla.Tags.FieldAttribute("Radiosity", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Sky Radiosity Light Block", 1, typeof(SkyRadiosityLightBlock))]
        public TagBlock Radiosity;
    }
}
#pragma warning restore CS1591
