#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(44, 4)]
    public class SoundEffectTemplatesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("dsp effect", typeof(StringId))]
        public StringId DspEffect;
        [Abide.Guerilla.Tags.FieldAttribute("explanation", typeof(Byte[]))]
        public Byte[] Explanation;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Int16))]
        public Int16 EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Int16))]
        public Int16 EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("parameters", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Sound Effect Template Parameter Block", 128, typeof(SoundEffectTemplateParameterBlock))]
        public TagBlock Parameters;
        public enum FlagsOptions
        {
            UseHighLevelParameters = 1,
            CustomParameters = 2,
        }
    }
}
#pragma warning restore CS1591
