#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    public class SoundEffectTemplateAdditionalSoundInputBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("dsp effect", typeof(StringId))]
        public StringId DspEffect;
        [Abide.Guerilla.Tags.FieldAttribute("low frequency sound", typeof(MappingFunctionBlock))]
        public MappingFunctionBlock LowFrequencySound1;
        [Abide.Guerilla.Tags.FieldAttribute("time period: seconds", typeof(Single))]
        public Single TimePeriod;
    }
}
#pragma warning restore CS1591
