#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(28, 4)]
    public class SoundSceneryDatumStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Volume Type", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(VolumeTypeOptions), false)]
        public Int32 VolumeType;
        [Abide.Guerilla.Tags.FieldAttribute("Height", typeof(Single))]
        public Single Height;
        [Abide.Guerilla.Tags.FieldAttribute("Override Outer Cone Gain:dB", typeof(Single))]
        public Single OverrideOuterConeGain;
        public enum VolumeTypeOptions
        {
            Sphere = 0,
            VerticalCylinder = 1,
        }
    }
}
#pragma warning restore CS1591
