#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(36, 4)]
    public class SoundEffectOverrideParametersBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("input", typeof(StringId))]
        public StringId Input;
        [Abide.Guerilla.Tags.FieldAttribute("range", typeof(StringId))]
        public StringId Range;
        [Abide.Guerilla.Tags.FieldAttribute("time period: seconds", typeof(Single))]
        public Single TimePeriod;
        [Abide.Guerilla.Tags.FieldAttribute("integer value", typeof(Int32))]
        public Int32 IntegerValue;
        [Abide.Guerilla.Tags.FieldAttribute("real value", typeof(Single))]
        public Single RealValue;
        [Abide.Guerilla.Tags.FieldAttribute("function value", typeof(MappingFunctionBlock))]
        public MappingFunctionBlock FunctionValue;
    }
}
#pragma warning restore CS1591
