#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(60, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("sound_looping", "lsnd", "����", typeof(SoundLoopingBlock))]
    public class SoundLoopingBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("marty\'s music time: seconds", typeof(Single))]
        public Single MartysMusicTime;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Single))]
        public Single EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagReference))]
        public TagReference EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("tracks#tracks play in parallel and loop continuously for the duration of the loop" +
            "ing sound.", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Looping Sound Track Block", 3, typeof(LoopingSoundTrackBlock))]
        public TagBlock Tracks;
        [Abide.Guerilla.Tags.FieldAttribute("detail sounds#detail sounds play at random throughout the duration of the looping" +
            " sound.", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Looping Sound Detail Block", 12, typeof(LoopingSoundDetailBlock))]
        public TagBlock DetailSounds;
        public enum FlagsOptions
        {
            DeafeningToAis = 1,
            NotALoop = 2,
            StopsMusic = 4,
            AlwaysSpatialize = 8,
            SynchronizePlayback = 16,
            SynchronizeTracks = 32,
            FakeSpatializationWithDistance = 64,
            CombineAll3dPlayback = 128,
        }
    }
}
#pragma warning restore CS1591
