#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(48, 4)]
    public class SpriteVerticesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Position*", typeof(Vector3))]
        public Vector3 Position;
        [Abide.Guerilla.Tags.FieldAttribute("Offset*", typeof(Vector3))]
        public Vector3 Offset;
        [Abide.Guerilla.Tags.FieldAttribute("Axis*", typeof(Vector3))]
        public Vector3 Axis;
        [Abide.Guerilla.Tags.FieldAttribute("texcoord*", typeof(Vector2))]
        public Vector2 Texcoord;
        [Abide.Guerilla.Tags.FieldAttribute("Color*", typeof(ColorRgb))]
        public ColorRgb Color;
    }
}
#pragma warning restore CS1591
