#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(96, 4)]
    public class StatesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("name^", typeof(String32))]
        public String32 Name;
        [Abide.Guerilla.Tags.FieldAttribute("color", typeof(ColorRgbF))]
        public ColorRgbF Color;
        [Abide.Guerilla.Tags.FieldAttribute("counts as:neighbors", typeof(Int16))]
        public Int16 CountsAs;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("initial placement weight", typeof(Single))]
        public Single InitialPlacementWeight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(24)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("zero", typeof(Int16))]
        public Int16 Zero;
        [Abide.Guerilla.Tags.FieldAttribute("one", typeof(Int16))]
        public Int16 One;
        [Abide.Guerilla.Tags.FieldAttribute("two", typeof(Int16))]
        public Int16 Two;
        [Abide.Guerilla.Tags.FieldAttribute("three", typeof(Int16))]
        public Int16 Three;
        [Abide.Guerilla.Tags.FieldAttribute("four", typeof(Int16))]
        public Int16 Four;
        [Abide.Guerilla.Tags.FieldAttribute("five", typeof(Int16))]
        public Int16 Five;
        [Abide.Guerilla.Tags.FieldAttribute("six", typeof(Int16))]
        public Int16 Six;
        [Abide.Guerilla.Tags.FieldAttribute("seven", typeof(Int16))]
        public Int16 Seven;
        [Abide.Guerilla.Tags.FieldAttribute("eight", typeof(Int16))]
        public Int16 Eight;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
    }
}
#pragma warning restore CS1591
