#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(16, 4)]
    public class StaticSpawnZoneDataStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Name", typeof(StringId))]
        public StringId Name;
        [Abide.Guerilla.Tags.FieldAttribute("Relevant Team", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(RelevantTeamOptions), true)]
        public Int32 RelevantTeam;
        [Abide.Guerilla.Tags.FieldAttribute("Relevant Games", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(RelevantGamesOptions), true)]
        public Int32 RelevantGames;
        [Abide.Guerilla.Tags.FieldAttribute("Flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        public enum RelevantTeamOptions
        {
            RedAlpha = 1,
            BlueBravo = 2,
            YellowCharlie = 4,
            GreenDelta = 8,
            PurpleEcho = 16,
            OrangeFoxtrot = 32,
            BrownGolf = 64,
            PinkHotel = 128,
            Neutral = 256,
        }
        public enum RelevantGamesOptions
        {
            Slayer = 1,
            Oddball = 2,
            KingOfTheHill = 4,
            CaptureTheFlag = 8,
            Race = 16,
            Headhunter = 32,
            Juggernaut = 64,
            Territories = 128,
        }
        public enum FlagsOptions
        {
            DisabledIfFlagHome = 1,
            DisabledIfFlagAway = 2,
            DisabledIfBombHome = 4,
            DisabledIfBombAway = 8,
        }
    }
}
#pragma warning restore CS1591
