#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(4, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("stereo_system", "BooM", "����", typeof(StereoSystemBlock))]
    public class StereoSystemBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("unused", typeof(Int32))]
        public Int32 Unused;
    }
}
#pragma warning restore CS1591
