#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class StructureBspSurfaceReferenceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Strip Index*", typeof(Int16))]
        public Int16 StripIndex;
        [Abide.Guerilla.Tags.FieldAttribute("Lightmap Triangle Index*", typeof(Int16))]
        public Int16 LightmapTriangleIndex;
        [Abide.Guerilla.Tags.FieldAttribute("BSP Node Index*", typeof(Int32))]
        public Int32 BspNodeIndex;
    }
}
#pragma warning restore CS1591
