#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class StructureBspLeafBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Cluster*", typeof(Int16))]
        public Int16 Cluster;
        [Abide.Guerilla.Tags.FieldAttribute("Surface Reference Count*", typeof(Int16))]
        public Int16 SurfaceReferenceCount;
        [Abide.Guerilla.Tags.FieldAttribute("First Surface Reference Index*", typeof(Int32))]
        public Int32 FirstSurfaceReferenceIndex;
    }
}
#pragma warning restore CS1591
