#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(36, 4)]
    public class StructureBspEnvironmentObjectPaletteBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Definition", typeof(TagReference))]
        public TagReference Definition;
        [Abide.Guerilla.Tags.FieldAttribute("Model", typeof(TagReference))]
        public TagReference Model;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
    }
}
#pragma warning restore CS1591
