#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(260, 4)]
    public class StructureBspInstancedGeometryDefinitionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Render Info", typeof(StructureInstancedGeometryRenderInfoStructBlock))]
        public StructureInstancedGeometryRenderInfoStructBlock RenderInfo;
        [Abide.Guerilla.Tags.FieldAttribute("Checksum*", typeof(Int32))]
        public Int32 Checksum;
        [Abide.Guerilla.Tags.FieldAttribute("Bounding Sphere Center", typeof(Vector3))]
        public Vector3 BoundingSphereCenter;
        [Abide.Guerilla.Tags.FieldAttribute("Bounding Sphere Radius", typeof(Single))]
        public Single BoundingSphereRadius;
        [Abide.Guerilla.Tags.FieldAttribute("Collision Info", typeof(GlobalCollisionBspStructBlock))]
        public GlobalCollisionBspStructBlock CollisionInfo;
        [Abide.Guerilla.Tags.FieldAttribute("bsp_physics*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Collision Bsp Physics Block", 1024, typeof(CollisionBspPhysicsBlock))]
        public TagBlock BspPhysics;
        [Abide.Guerilla.Tags.FieldAttribute("Render Leaves*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Structure Bsp Leaf Block", 65536, typeof(StructureBspLeafBlock))]
        public TagBlock RenderLeaves;
        [Abide.Guerilla.Tags.FieldAttribute("Surface References*", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Structure Bsp Surface Reference Block", 262144, typeof(StructureBspSurfaceReferenceBlock))]
        public TagBlock SurfaceReferences;
    }
}
#pragma warning restore CS1591
