#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(220, 4)]
    public class StructureLightmapLightingEnvironmentBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("sample_point*", typeof(Vector3))]
        public Vector3 SamplePoint;
        [Abide.Guerilla.Tags.FieldAttribute("red coefficients*", typeof(Byte[]))]
        public Byte[] RedCoefficients;
        [Abide.Guerilla.Tags.FieldAttribute("red coefficient*", typeof(Single))]
        public Single RedCoefficient;
        [Abide.Guerilla.Tags.FieldAttribute("green coefficients*", typeof(Byte[]))]
        public Byte[] GreenCoefficients;
        [Abide.Guerilla.Tags.FieldAttribute("green coefficient*", typeof(Single))]
        public Single GreenCoefficient;
        [Abide.Guerilla.Tags.FieldAttribute("blue coefficients*", typeof(Byte[]))]
        public Byte[] BlueCoefficients;
        [Abide.Guerilla.Tags.FieldAttribute("blue coefficient*", typeof(Single))]
        public Single BlueCoefficient;
        [Abide.Guerilla.Tags.FieldAttribute("mean incoming light direction", typeof(Vector3))]
        public Vector3 MeanIncomingLightDirection;
        [Abide.Guerilla.Tags.FieldAttribute("incoming light intensity", typeof(Vector3))]
        public Vector3 IncomingLightIntensity;
        [Abide.Guerilla.Tags.FieldAttribute("specular bitmap index", typeof(Int32))]
        public Int32 SpecularBitmapIndex;
        [Abide.Guerilla.Tags.FieldAttribute("rotation axis", typeof(Vector3))]
        public Vector3 RotationAxis;
        [Abide.Guerilla.Tags.FieldAttribute("rotation speed", typeof(Single))]
        public Single RotationSpeed;
        [Abide.Guerilla.Tags.FieldAttribute("bump direction", typeof(Vector3))]
        public Vector3 BumpDirection;
        [Abide.Guerilla.Tags.FieldAttribute("color tint", typeof(ColorRgbF))]
        public ColorRgbF ColorTint;
        [Abide.Guerilla.Tags.FieldAttribute("procedural overide", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ProceduralOverideOptions), false)]
        public Int16 ProceduralOveride;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("procedural param0", typeof(Vector3))]
        public Vector3 ProceduralParam0;
        [Abide.Guerilla.Tags.FieldAttribute("procedural param1.xyz", typeof(Vector3))]
        public Vector3 ProceduralParam1xyz;
        [Abide.Guerilla.Tags.FieldAttribute("procedural param1.w", typeof(Single))]
        public Single ProceduralParam1w;
        public enum ProceduralOverideOptions
        {
            NoOveride = 0,
            CieClearSky = 1,
            CiePartlyCloudy = 2,
            CieCloudy = 3,
            DirectionalLight = 4,
            ConeLight = 5,
            SphereLight = 6,
            HemisphereLight = 7,
        }
        public enum FlagsOptions
        {
            LeaveMeAlonePlease = 1,
        }
    }
}
#pragma warning restore CS1591
