#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(92, 4)]
    public class StructureBspFakeLightprobesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Object Identifier*", typeof(ScenarioObjectIdStructBlock))]
        public ScenarioObjectIdStructBlock ObjectIdentifier;
        [Abide.Guerilla.Tags.FieldAttribute("Render Lighting*", typeof(RenderLightingStructBlock))]
        public RenderLightingStructBlock RenderLighting;
    }
}
#pragma warning restore CS1591
