#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 8)]
    public class SurfacesBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Plane*", typeof(Int16))]
        public Int16 Plane;
        [Abide.Guerilla.Tags.FieldAttribute("First Edge*", typeof(Int16))]
        public Int16 FirstEdge;
        [Abide.Guerilla.Tags.FieldAttribute("Flags*", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(Flags), true)]
        public Byte Flags1;
        [Abide.Guerilla.Tags.FieldAttribute("Breakable Surface*", typeof(Byte))]
        public Byte BreakableSurface;
        [Abide.Guerilla.Tags.FieldAttribute("Material*", typeof(Int16))]
        public Int16 Material;
        public enum Flags
        {
            Twosided = 1,
            Invisible = 2,
            Climbable = 4,
            Breakable = 8,
            Invalid = 16,
            Conveyor = 32,
        }
    }
}
#pragma warning restore CS1591
