#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(52, 4)]
    public class UiErrorCategoryBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("category name^", typeof(StringId))]
        public StringId CategoryName;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("default button", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(DefaultButtonOptions), false)]
        public Byte DefaultButton;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(1)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("string tag", typeof(TagReference))]
        public TagReference StringTag;
        [Abide.Guerilla.Tags.FieldAttribute("default title", typeof(StringId))]
        public StringId DefaultTitle;
        [Abide.Guerilla.Tags.FieldAttribute("default message", typeof(StringId))]
        public StringId DefaultMessage;
        [Abide.Guerilla.Tags.FieldAttribute("default ok", typeof(StringId))]
        public StringId DefaultOk;
        [Abide.Guerilla.Tags.FieldAttribute("default cancel", typeof(StringId))]
        public StringId DefaultCancel;
        [Abide.Guerilla.Tags.FieldAttribute("error block", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Ui Error Block", 100, typeof(UiErrorBlock))]
        public TagBlock ErrorBlock;
        public enum FlagsOptions
        {
            UseLargeDialog = 1,
        }
        public enum DefaultButtonOptions
        {
            NoDefault = 0,
            DefaultOk = 1,
            DefaultCancel = 2,
        }
    }
}
#pragma warning restore CS1591
