#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(80, 4)]
    public class UnitBoardingMeleeStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("boarding melee damage", typeof(TagReference))]
        public TagReference BoardingMeleeDamage;
        [Abide.Guerilla.Tags.FieldAttribute("boarding melee response", typeof(TagReference))]
        public TagReference BoardingMeleeResponse;
        [Abide.Guerilla.Tags.FieldAttribute("landing melee damage", typeof(TagReference))]
        public TagReference LandingMeleeDamage;
        [Abide.Guerilla.Tags.FieldAttribute("flurry melee damage", typeof(TagReference))]
        public TagReference FlurryMeleeDamage;
        [Abide.Guerilla.Tags.FieldAttribute("obstacle smash damage", typeof(TagReference))]
        public TagReference ObstacleSmashDamage;
    }
}
#pragma warning restore CS1591
