#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(20, 4)]
    public class UnitSeatAccelerationStructBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("acceleration range:world units per second squared", typeof(Vector3))]
        public Vector3 AccelerationRange;
        [Abide.Guerilla.Tags.FieldAttribute("accel action scale:actions fail [0,1+]", typeof(Single))]
        public Single AccelActionScale;
        [Abide.Guerilla.Tags.FieldAttribute("accel attach scale:detach unit [0,1+]", typeof(Single))]
        public Single AccelAttachScale;
    }
}
#pragma warning restore CS1591
