#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(56, 4)]
    public class UnitHudSoundBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("sound^", typeof(TagReference))]
        public TagReference Sound;
        [Abide.Guerilla.Tags.FieldAttribute("latched to", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(LatchedToOptions), true)]
        public Int32 LatchedTo;
        [Abide.Guerilla.Tags.FieldAttribute("scale", typeof(Single))]
        public Single Scale;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString;
        public enum LatchedToOptions
        {
            ShieldRecharging = 1,
            ShieldDamaged = 2,
            ShieldLow = 4,
            ShieldEmpty = 8,
            HealthLow = 16,
            HealthEmpty = 32,
            HealthMinorDamage = 64,
            HealthMajorDamage = 128,
        }
    }
}
#pragma warning restore CS1591
