#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(8, 4)]
    public class UserHintJumpBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("Flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("geometry index*", typeof(Int16))]
        public Int16 GeometryIndex;
        [Abide.Guerilla.Tags.FieldAttribute("force jump height", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ForceJumpHeightOptions), false)]
        public Int16 ForceJumpHeight;
        [Abide.Guerilla.Tags.FieldAttribute("control flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ControlFlagsOptions), true)]
        public Int16 ControlFlags;
        public enum FlagsOptions
        {
            Bidirectional = 1,
            Closed = 2,
        }
        public enum ForceJumpHeightOptions
        {
            None = 0,
            Down = 1,
            Step = 2,
            Crouch = 3,
            Stand = 4,
            Storey = 5,
            Tower = 6,
            Infinite = 7,
        }
        public enum ControlFlagsOptions
        {
            MagicLift = 1,
        }
    }
}
#pragma warning restore CS1591
