#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(32, 4)]
    public class UserHintWellPointBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(TypeOptions), false)]
        public Int16 Type;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("point", typeof(Vector3))]
        public Vector3 Point;
        [Abide.Guerilla.Tags.FieldAttribute("reference frame", typeof(Int16))]
        public Int16 ReferenceFrame;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("sector index", typeof(Int32))]
        public Int32 SectorIndex;
        [Abide.Guerilla.Tags.FieldAttribute("normal", typeof(Vector2))]
        public Vector2 Normal;
        public enum TypeOptions
        {
            Jump = 0,
            Climb = 1,
            Hoist = 2,
        }
    }
}
#pragma warning restore CS1591
