#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(140, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("user_interface_screen_widget_definition", "wgit", "����", typeof(UserInterfaceScreenWidgetDefinitionBlock))]
    public class UserInterfaceScreenWidgetDefinitionBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags1;
        [Abide.Guerilla.Tags.FieldAttribute("screen ID", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ScreenIdOptions), false)]
        public Int16 ScreenId;
        [Abide.Guerilla.Tags.FieldAttribute("button key type", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ButtonKeyTypeOptions), false)]
        public Int16 ButtonKeyType;
        [Abide.Guerilla.Tags.FieldAttribute("text color", typeof(ColorArgbF))]
        public ColorArgbF TextColor;
        [Abide.Guerilla.Tags.FieldAttribute("string list tag", typeof(TagReference))]
        public TagReference StringListTag;
        [Abide.Guerilla.Tags.FieldAttribute("panes", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Window Pane Reference Block", 16, typeof(WindowPaneReferenceBlock))]
        public TagBlock Panes1;
        [Abide.Guerilla.Tags.FieldAttribute("shape group", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ShapeGroupOptions), false)]
        public Int16 ShapeGroup1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("header string id", typeof(StringId))]
        public StringId HeaderStringId;
        [Abide.Guerilla.Tags.FieldAttribute("local strings", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Local String Id List Section Reference Block", 16, typeof(LocalStringIdListSectionReferenceBlock))]
        public TagBlock LocalStrings1;
        [Abide.Guerilla.Tags.FieldAttribute("local bitmaps", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Local Bitmap Reference Block", 16, typeof(LocalBitmapReferenceBlock))]
        public TagBlock LocalBitmaps1;
        [Abide.Guerilla.Tags.FieldAttribute("source color", typeof(ColorRgbF))]
        public ColorRgbF SourceColor;
        [Abide.Guerilla.Tags.FieldAttribute("destination color", typeof(ColorRgbF))]
        public ColorRgbF DestinationColor;
        [Abide.Guerilla.Tags.FieldAttribute("accumulate zoom scale x", typeof(Single))]
        public Single AccumulateZoomScaleX;
        [Abide.Guerilla.Tags.FieldAttribute("accumulate zoom scale y", typeof(Single))]
        public Single AccumulateZoomScaleY;
        [Abide.Guerilla.Tags.FieldAttribute("refraction scale x", typeof(Single))]
        public Single RefractionScaleX;
        [Abide.Guerilla.Tags.FieldAttribute("refraction scale y", typeof(Single))]
        public Single RefractionScaleY;
        [Abide.Guerilla.Tags.FieldAttribute("mouse cursor definition", typeof(TagReference))]
        public TagReference MouseCursorDefinition;
        public enum FlagsOptions
        {
            _14ScreenDialog = 1,
            MultiplePanesAreForListFlavorItems = 2,
            NoHeaderText = 4,
            _12ScreenDialog = 8,
            LargeDialog = 16,
            DisableOverlayEffect = 32,
        }
        public enum ScreenIdOptions
        {
            Test = 0,
            Test1 = 1,
            Test2 = 2,
            Test3 = 3,
            Test4 = 4,
            GameShellBackground = 5,
            MainMenu = 6,
            ErrorDialogOkCancel = 7,
            ErrorDialogOk = 8,
            PressStartIntro = 9,
            PlayerProfileSelect = 10,
            SpLevelSelect = 11,
            SpDifficultySelect = 12,
            NetworkSquadBrowser = 13,
            MpPregameLobby = 14,
            CustomGameMenu = 15,
            PostgameStats = 16,
            MpMapSelect = 17,
            SpPauseGame = 18,
            Settings = 19,
            GamertagSelect = 20,
            GamertagPasscodeEntry = 21,
            MultiplayerProtocol = 22,
            SquadSettings = 23,
            SquadGameSettings = 24,
            SquadPrivacySettings = 25,
            YMenugameshell = 26,
            YMenugameshellCollapsed = 27,
            YMenuingame = 28,
            YMenuingameCollapsed = 29,
            _4wayJoinScreen = 30,
            YMenuplayerSelectedOptions = 31,
            PlayerSelectedOptions = 32,
            ConfirmationDialog = 33,
            LiveFeedbackMenuDialog = 34,
            LiveMessageTypeDialog = 35,
            VoiceMsgDialog = 36,
            StereoFaceplate = 37,
            PlayerProfileEditMenu = 38,
            PpControllerSettings = 39,
            PpButtonSettings = 40,
            PpThumbstickSettings = 41,
            PpLookSensitivitySettings = 42,
            PpInvertLookSettings = 43,
            PpAutolevelSettings = 44,
            PpHandicapSettings = 45,
            PpHighScoreRecSettings = 46,
            PpMultiplayerSettingsMenu = 47,
            PpProfileDeleteConfirmationDlg = 48,
            PpChooseForegroundEmblem = 49,
            PpChoosePrimaryColor = 50,
            PpChooseSecondaryColor = 51,
            PpChooseModel = 52,
            PpVoiceSettingsMenu = 53,
            PpChooseVoiceMask = 54,
            PpVoiceThruTv = 55,
            PpEditRotationList = 56,
            PpXblStatusMenu = 57,
            PpAppearOffline = 58,
            PpAutooffline = 59,
            GameEngineCategoryListing = 60,
            EditSlayerMenu = 61,
            EditKothMenu = 62,
            EditRaceMenu = 63,
            EditOddballMenu = 64,
            EditJuggernautMenu = 65,
            EditHeadhunterMenu = 66,
            EditCtfMenu = 67,
            EditAssaultMenu = 68,
            EditSlayerScoreToWin = 69,
            EditSlayerTimeLimit = 70,
            EditSlayerTeams = 71,
            EditSlayerScore4Killing = 72,
            EditSlayerKillInOrder = 73,
            EditSlayerDeathPtLoss = 74,
            EditSlayerSuicidePtLoss = 75,
            EditSlayerDmgAfterKill = 76,
            EditSlayerDmgAfterDeath = 77,
            EditSlayerSpeedAfterKill = 78,
            EditSlayerSpeedAfterDeath = 79,
            EditKothScoreToWin = 80,
            EditKothTimeLimit = 81,
            EditKothTeams = 82,
            EditKothMovingHills = 83,
            EditKothUncontesedControl = 84,
            EditKothXtraDmg = 85,
            EditRaceLapsToWin = 86,
            EditRaceTimeLimit = 87,
            EditRaceTeams = 88,
            EditRaceTeamScoring = 89,
            EditRaceType = 90,
            EditRaceFlagOrder = 91,
            EditRaceGameEndCondition = 92,
            EditRaceDmgWithLaps = 93,
            EditRaceSpeedWithLaps = 94,
            EditOddballTimeToWin = 95,
            EditOddballTimeLimit = 96,
            EditOddballTeams = 97,
            EditOddballBallSpawnCount = 98,
            EditOddballBallWaypoints = 99,
            EditOddballDamageWithBall = 100,
            EditOddballSpeedWithBall = 101,
            EditOddballInvisibilityWithBall = 102,
            EditJugScoreToWin = 103,
            EditJugTimeLimit = 104,
            EditJugPtsForKillingJugger = 105,
            EditJugCount = 106,
            EditJugSpecies = 107,
            EditJugStartingEquip = 108,
            EditJugDamage = 109,
            EditJugHealth = 110,
            EditJugSpeed = 111,
            EditJugRegeneration = 112,
            EditJugWaypoints = 113,
            EditHhScoreToWin = 114,
            EditHhTimeLimit = 115,
            EditHhTeams = 116,
            EditHhDeathPtLoss = 117,
            EditHhSuicidePtLoss = 118,
            EditHhSpeedWithToken = 119,
            EditHhDroppedTokenLifetime = 120,
            EditHhScoreMultiplier = 121,
            EditCtfScoreToWin = 122,
            EditCtfTimeLimit = 123,
            EditCtfTieResolution = 124,
            EditCtfSingleFlag = 125,
            EditCtfRoleSwapping = 126,
            EditCtfFlagAtHomeToScore = 127,
            EditCtfFlagMustReset = 128,
            EditCtfDmgWithFlag = 129,
            EditCtfSpeedWithFlag = 130,
            EditAssaultScoreToWin = 131,
            EditAssaultTimeLimit = 132,
            EditAssaultTieResolution = 133,
            EditAssaultSingleFlag = 134,
            EditAssaultRoleSwapping = 135,
            EditAssaultEnemyFlagAtHomeToScore = 136,
            EditAssaultFlagMustReset = 137,
            EditAssaultDmgWithFlag = 138,
            EditAssaultSpeedWithFlag = 139,
            EditPlayerNumberOfLives = 140,
            EditPlayerMaxHealth = 141,
            EditPlayerShields = 142,
            EditPlayerRespawnTime = 143,
            EditPlayerCount = 144,
            EditPlayerInvisibility = 145,
            EditPlayerSuicidePenalty = 146,
            EditPlayerFriendlyFire = 147,
            EditItemRespawnGrenades = 148,
            EditItemPowerups = 149,
            EditItemWeaponSet = 150,
            EditItemStartingEquipment = 151,
            EditItemWarthogs = 152,
            EditItemGhosts = 153,
            EditItemScorpions = 154,
            EditItemBanshees = 155,
            EditItemMongeese = 156,
            EditItemShadows = 157,
            EditItemWraiths = 158,
            EditIndicatorObjectives = 159,
            EditIndicatorPlayersOnMotionSensor = 160,
            EditIndicatorInvisiblePlayersOnMotionSensor = 161,
            EditIndicatorFriends = 162,
            EditIndicatorEnemies = 163,
            EditPlayerOptions = 164,
            EditItemOptions = 165,
            EditIndicatorOptions = 166,
            VirtualKeyboard = 167,
            CustomGameMenu1 = 168,
            SlayerQuickOptions = 169,
            KothQuickOptions = 170,
            RaceQuickOptions = 171,
            OddballQuickOptions = 172,
            JuggerQuickOptions = 173,
            HhQuickOptions = 174,
            CtfQuickOptions = 175,
            AssaultQuickOptions = 176,
            PickNewSquadLeader = 177,
            VariantEditingOptionsMenu = 178,
            PlaylistListsettings = 179,
            PlaylistContents = 180,
            PlaylistSelectedOptions = 181,
            XboxLiveTaskProgress = 182,
            PpVibrationSettings = 183,
            BootPlayerDialog = 184,
            PostgameStatslobby = 185,
            XboxLiveMainMenu = 186,
            EditTerriesMenu = 187,
            EditTerriesScoreToWin = 188,
            EditTerriesTimeLimit = 189,
            EditTerriesTeams = 190,
            TerriesQuickOptions = 191,
            XboxLiveNotificationBeeper = 192,
            PlayerProfileSelectfancy = 193,
            SavedGameFileActionsDialog = 194,
            MpStartMenu = 195,
            MpStartPlayerSettings = 196,
            MpStartHandicapSettings = 197,
            MpStartChangeTeams = 198,
            MpStartAdminSettings = 199,
            MpStartControllerSettings = 200,
            MpStartVoiceSettings = 201,
            MpStartOnlineStatus = 202,
            MpalphaLegalWarning = 203,
            SquadJoinProgressDialog = 204,
            MpAlphaPostgameLegalWarning = 205,
            MpMapSelectlobby = 206,
            MpVariantTypelobby = 207,
            MpVariantListlobby = 208,
            LoadingProgress = 209,
            MatchmakingProgress = 210,
            LiveMessageDisplay = 211,
            FadeinFromBlack = 212,
            LivePlayerProfile = 213,
            LiveClanProfile = 214,
            LiveMessageSend = 215,
            FriendsOptionsDialog = 216,
            ClanOptionsDialog = 217,
            CampaignOptionsDialog = 218,
            OptimatchHoppersFullscreen = 219,
            PlaylistListdialog = 220,
            VariantEditingFormat = 221,
            VariantQuickOptionsFormat = 222,
            VariantParamSettingFormat = 223,
            VehicleOptions = 224,
            MatchOptions = 225,
            PlayerOptions = 226,
            TeamOptions = 227,
            GameOptions = 228,
            EquipmentOptions = 229,
            MultipleChoiceDialog = 230,
            NetworkTransitionProgress = 231,
            XboxLiveStats = 232,
            PpChooseBackgroundEmblem = 233,
            PpButtonsQtr = 234,
            PpStixQtr = 235,
            ClanMemberPrivs = 236,
            OptimatchHoppersLobby = 237,
            SavedGameFileDialog = 238,
            Xyzzy = 239,
            ErrorOkCancelLarge = 240,
            Yzzyx = 241,
            SubtitleDisplay = 242,
            PpKeyboardSettings = 243,
            PpKeyboardSettingsQtr = 244,
            PpInvertDualWield = 245,
            SystemSettings = 246,
            BungieNews = 247,
            FilterSelect = 248,
            LiveGameBrowser = 249,
            GameDetails = 250,
            MpCustomMapSelect = 251,
            MpAllMapsSelect = 252,
            PpAdvancedKeyboardSettings = 253,
            PpAdvancedKeyboardSettingsQtr = 254,
            NetworkAdapterSettings = 255,
        }
        public enum ButtonKeyTypeOptions
        {
            None = 0,
            AEqualsSelectBEqualsBack = 1,
            AEqualsSelectBEqualsCancel = 2,
            AEqualsEnterBEqualsCancel = 3,
            YEqualsXboxLivePlayers = 4,
            XEqualsFriendsOptions = 5,
            XEqualsClanOptions = 6,
            XEqualsRecentPlayersOptions = 7,
            XEqualsOptions = 8,
            AEqualsSelect = 9,
            XEqualsSettingsAEqualsSelectBEqualsBack = 10,
            XEqualsDeleteAEqualsSelectBEqualsDone = 11,
            AEqualsAccept = 12,
            BEqualsCancel = 13,
            YEqualsXboxLivePlayersAEqualsSelectBEqualsBack = 14,
            YEqualsXboxLivePlayersAEqualsSelectBEqualsCancel = 15,
            YEqualsXboxLivePlayersAEqualsEnterBEqualsCancel = 16,
            YEqualsXboxLivePlayersAEqualsSelect = 17,
            YEqualsXboxLivePlayersAEqualsSelectBEqualsDone = 18,
            YEqualsXboxLivePlayersAEqualsAccept = 19,
            YEqualsXboxLivePlayersBEqualsCancel = 20,
            XEqualsDeleteAEqualsSelectBEqualsBack = 21,
            AEqualsOk = 22,
        }
        public enum ShapeGroupOptions
        {
            None = 0,
            _00 = 1,
            _01 = 2,
            _02 = 3,
            _03 = 4,
            _04 = 5,
            _05 = 6,
            _06 = 7,
            _07 = 8,
            _08 = 9,
            _09 = 10,
            _10 = 11,
            _11 = 12,
            _12 = 13,
            _13 = 14,
            _14 = 15,
            _15 = 16,
            _16 = 17,
            _17 = 18,
            _18 = 19,
            _19 = 20,
            _20 = 21,
            _21 = 22,
            _22 = 23,
            _23 = 24,
            _24 = 25,
            _25 = 26,
            _26 = 27,
            _27 = 28,
            _28 = 29,
            _29 = 30,
            _30 = 31,
            _31 = 32,
        }
    }
}
#pragma warning restore CS1591
