#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(672, 16)]
    public class VehiclePhantomShapeBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("size*", typeof(Int16))]
        public Int16 Size;
        [Abide.Guerilla.Tags.FieldAttribute("count*", typeof(Int16))]
        public Int16 Count;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("child shapes size*", typeof(Int32))]
        public Int32 ChildShapesSize;
        [Abide.Guerilla.Tags.FieldAttribute("child shapes capacity*", typeof(Int32))]
        public Int32 ChildShapesCapacity;
        [Abide.Guerilla.Tags.FieldAttribute("child shapes storage*", typeof(Byte[]))]
        public Byte[] ChildShapesStorage;
        [Abide.Guerilla.Tags.FieldAttribute("shape type*", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(ShapeType), false)]
        public Int16 ShapeType1;
        [Abide.Guerilla.Tags.FieldAttribute("shape*", typeof(Int16))]
        public Int16 Shape;
        [Abide.Guerilla.Tags.FieldAttribute("collision filter*", typeof(Int32))]
        public Int32 CollisionFilter;
        [Abide.Guerilla.Tags.FieldAttribute("multisphere count*", typeof(Int32))]
        public Int32 MultisphereCount;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int32))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int32 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(8)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("x0", typeof(Single))]
        public Single X0;
        [Abide.Guerilla.Tags.FieldAttribute("x1", typeof(Single))]
        public Single X1;
        [Abide.Guerilla.Tags.FieldAttribute("y0", typeof(Single))]
        public Single Y0;
        [Abide.Guerilla.Tags.FieldAttribute("y1", typeof(Single))]
        public Single Y1;
        [Abide.Guerilla.Tags.FieldAttribute("z0", typeof(Single))]
        public Single Z0;
        [Abide.Guerilla.Tags.FieldAttribute("z1", typeof(Single))]
        public Single Z1;
        [Abide.Guerilla.Tags.FieldAttribute("multispheres*", typeof(Byte[]))]
        public Byte[] Multispheres;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("size*", typeof(Int16))]
        public Int16 Size1;
        [Abide.Guerilla.Tags.FieldAttribute("count*", typeof(Int16))]
        public Int16 Count1;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("num spheres*", typeof(Int32))]
        public Int32 NumSpheres;
        [Abide.Guerilla.Tags.FieldAttribute("four vectors storage*", typeof(Byte[]))]
        public Byte[] FourVectorsStorage;
        [Abide.Guerilla.Tags.FieldAttribute("sphere*", typeof(Vector3))]
        public Vector3 Sphere;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString7;
        public enum ShapeType
        {
            Sphere = 0,
            Pill = 1,
            Box = 2,
            Triangle = 3,
            Polyhedron = 4,
            MultiSphere = 5,
            Unused0 = 6,
            Unused1 = 7,
            Unused2 = 8,
            Unused3 = 9,
            Unused4 = 10,
            Unused5 = 11,
            Unused6 = 12,
            Unused7 = 13,
            List = 14,
            Mopp = 15,
        }
        public enum FlagsOptions
        {
            HasAabbPhantom = 1,
            Oo1 = 2,
        }
    }
}
#pragma warning restore CS1591
