#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abide.Guerilla.Tags2
{
    using Abide.Guerilla.Types;
    using Abide.HaloLibrary;
    using System;
    
    [Abide.Guerilla.Tags.FieldSetAttribute(380, 4)]
    [Abide.Guerilla.Tags.TagGroupAttribute("weapon_hud_interface", "wphi", "����", typeof(WeaponHudInterfaceBlock))]
    public class WeaponHudInterfaceBlock
    {
        [Abide.Guerilla.Tags.FieldAttribute("child hud", typeof(TagReference))]
        public TagReference ChildHud;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions), true)]
        public Int16 Flags;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString;
        [Abide.Guerilla.Tags.FieldAttribute("inventory ammo cutoff", typeof(Int16))]
        public Int16 InventoryAmmoCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("loaded ammo cutoff", typeof(Int16))]
        public Int16 LoadedAmmoCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("heat cutoff", typeof(Int16))]
        public Int16 HeatCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("age cutoff", typeof(Int16))]
        public Int16 AgeCutoff;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString1;
        [Abide.Guerilla.Tags.FieldAttribute("anchor", typeof(Int16))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(AnchorOptions), false)]
        public Int16 Anchor;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(2)]
        public Byte[] EmptyString2;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(32)]
        public Byte[] EmptyString3;
        [Abide.Guerilla.Tags.FieldAttribute("static elements", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapon Hud Static Block", 16, typeof(WeaponHudStaticBlock))]
        public TagBlock StaticElements;
        [Abide.Guerilla.Tags.FieldAttribute("meter elements", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapon Hud Meter Block", 16, typeof(WeaponHudMeterBlock))]
        public TagBlock MeterElements;
        [Abide.Guerilla.Tags.FieldAttribute("number elements", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapon Hud Number Block", 16, typeof(WeaponHudNumberBlock))]
        public TagBlock NumberElements;
        [Abide.Guerilla.Tags.FieldAttribute("crosshairs", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapon Hud Crosshair Block", 19, typeof(WeaponHudCrosshairBlock))]
        public TagBlock Crosshairs1;
        [Abide.Guerilla.Tags.FieldAttribute("overlay elements", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Weapon Hud Overlays Block", 16, typeof(WeaponHudOverlaysBlock))]
        public TagBlock OverlayElements;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(4)]
        public Byte[] EmptyString4;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("G Null Block", 0, typeof(GNullBlock))]
        public TagBlock EmptyString5;
        [Abide.Guerilla.Tags.FieldAttribute("screen effect", typeof(TagBlock))]
        [Abide.Guerilla.Tags.BlockAttribute("Global Hud Screen Effect Definition", 1, typeof(GlobalHudScreenEffectDefinition))]
        public TagBlock ScreenEffect;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(132)]
        public Byte[] EmptyString6;
        [Abide.Guerilla.Tags.FieldAttribute("sequence index#sequence index into the global hud icon bitmap", typeof(Int16))]
        public Int16 SequenceIndex;
        [Abide.Guerilla.Tags.FieldAttribute("width offset#extra spacing beyond bitmap width for text alignment", typeof(Int16))]
        public Int16 WidthOffset;
        [Abide.Guerilla.Tags.FieldAttribute("offset from reference corner", typeof(Vector2))]
        public Vector2 OffsetFromReferenceCorner;
        [Abide.Guerilla.Tags.FieldAttribute("override icon color", typeof(ColorArgb))]
        public ColorArgb OverrideIconColor;
        [Abide.Guerilla.Tags.FieldAttribute("frame rate [0,30]", typeof(Byte))]
        public Byte FrameRate030;
        [Abide.Guerilla.Tags.FieldAttribute("flags", typeof(Byte))]
        [Abide.Guerilla.Tags.OptionsAttribute(typeof(FlagsOptions1), true)]
        public Byte Flags1;
        [Abide.Guerilla.Tags.FieldAttribute("text index", typeof(Int16))]
        public Int16 TextIndex;
        [Abide.Guerilla.Tags.FieldAttribute("", typeof(Byte[]))]
        [Abide.Guerilla.Tags.PaddingAttribute(48)]
        public Byte[] EmptyString7;
        public enum FlagsOptions
        {
            UseParentHudFlashingParameters = 1,
        }
        public enum AnchorOptions
        {
            TopLeft = 0,
            TopRight = 1,
            BottomLeft = 2,
            BottomRight = 3,
            Center = 4,
            Crosshair = 5,
        }
        public enum FlagsOptions1
        {
            UseTextFromStringListInstead = 1,
            OverrideDefaultColor = 2,
            WidthOffsetIsAbsoluteIconWidth = 4,
        }
    }
}
#pragma warning restore CS1591
